import test from"node:test";import assert from"node:assert/strict";import{mkdtemp,rm}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{initializeAuthoritativeGcTombstoneV1,evaluateGcEligibilityV1,commitGcTombstoneV1,validateBlobDeletionAgainstTombstoneV1,readAuthoritativeGcTombstoneV1}from"../runtime/rev51/authoritative-gc-tombstone-v1.mjs";const H=x=>x.repeat(64),T=Date.parse("2026-09-24T00:00:00Z");async function fx(){const d=await mkdtemp(join(tmpdir(),"p2j-"));return{d,p:join(d,"g.json")}};const input=()=>({AUTHORITATIVE_ACCEPTANCE:true,PROVIDER_SAGA_COMPLETE:true,EXECUTION_TRANSPORT_DEREGISTERED:true,REQUIRED_RESOURCE_CLEANUP_TERMINAL:true,BILLING_STATUS:"STOPPED",ACCEPTANCE_JOURNAL_SHA256:H("a"),EXECUTION_RECEIPT_SHA256:H("b"),ARTIFACT_MANIFEST_SHA256:H("c"),CONTENT_SHA256:H("d")});
for(const [field,code] of [["AUTHORITATIVE_ACCEPTANCE","AUTHORITATIVE_ACCEPTANCE_REQUIRED"],["PROVIDER_SAGA_COMPLETE","PROVIDER_SAGA_NOT_COMPLETE"],["EXECUTION_TRANSPORT_DEREGISTERED","TRANSPORT_NOT_DEREGISTERED"],["REQUIRED_RESOURCE_CLEANUP_TERMINAL","RESOURCE_CLEANUP_NOT_TERMINAL"]])test(`${field} required`,()=>{const x=input();x[field]=false;assert.deepEqual(evaluateGcEligibilityV1(x),{ok:false,code})});
test("billing terminal required",()=>{const x=input();x.BILLING_STATUS="ACTIVE";assert.equal(evaluateGcEligibilityV1(x).ok,false)});test("eligible terminal state",()=>assert.deepEqual(evaluateGcEligibilityV1(input()),{ok:true,code:"GC_ELIGIBLE"}));
test("commit tombstone then deletion allowed",async()=>{const f=await fx();try{await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);const r=await commitGcTombstoneV1(f.p,input(),{ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1});assert.deepEqual(validateBlobDeletionAgainstTombstoneV1(r.state,"a1",H("d")),{ok:true,code:"AUTHORITATIVE_BLOB_DELETION_ALLOWED"})}finally{await rm(f.d,{recursive:true,force:true})}});
test("deletion before tombstone denied",async()=>{const f=await fx();try{const s=await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);assert.equal(validateBlobDeletionAgainstTombstoneV1(s,"a1",H("d")).code,"GC_TOMBSTONE_REQUIRED")}finally{await rm(f.d,{recursive:true,force:true})}});
test("content mismatch denied",async()=>{const f=await fx();try{await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);const r=await commitGcTombstoneV1(f.p,input(),{ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1});assert.equal(validateBlobDeletionAgainstTombstoneV1(r.state,"a1",H("f")).code,"GC_CONTENT_HASH_MISMATCH")}finally{await rm(f.d,{recursive:true,force:true})}});
test("reopen preserves tombstone",async()=>{const f=await fx();try{await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);await commitGcTombstoneV1(f.p,input(),{ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1});assert.ok((await readAuthoritativeGcTombstoneV1(f.p)).TOMBSTONES.a1)}finally{await rm(f.d,{recursive:true,force:true})}});
test("same replay pass",async()=>{const f=await fx();try{await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);const q={ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1};await commitGcTombstoneV1(f.p,input(),q);assert.equal((await commitGcTombstoneV1(f.p,input(),{...q,RUNTIME_NOW_MS:T+2})).replay,true)}finally{await rm(f.d,{recursive:true,force:true})}});
test("second tombstone denied",async()=>{const f=await fx();try{await initializeAuthoritativeGcTombstoneV1(f.p,{EXECUTION_PLAN_SHA256:H("e")},T);await commitGcTombstoneV1(f.p,input(),{ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1});await assert.rejects(commitGcTombstoneV1(f.p,input(),{ARTIFACT_ID:"a1",IDEMPOTENCY_KEY:"k2",EXPECTED_STATE_VERSION:1,RUNTIME_NOW_MS:T+2}),/ARTIFACT_ALREADY_TOMBSTONED/)}finally{await rm(f.d,{recursive:true,force:true})}});
