import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

import { verifyRuntimeRev52HandoffV1, validatePiloteRuntimeDependencyLockV1 } from "../pilote/rev52/runtime-dependency-bind-v1.mjs";
import { compileAuthoritativePlanV1, compileMasterPlanDependencyGraphV1, compileProjectRunGrantV1, compilePhaseExecutionGrantV1, compileSourceProgressPolicyV1, compileExplicitDependencyV1, interpretRuntimeProjectRunStateV2V1 } from "../pilote/rev52/plan-grant-source-progress-v1.mjs";
import { collectAuthRequirementsV1, compileFinalAuthBindPolicyV1, compileRuntimeAuthEligibilityRequestV1, compileSourceMutationAuthorityRequestV1, compileAuthorityBoundaryV1, compileLeastPrivilegeStagingV1 } from "../pilote/rev52/auth-authority-policy-v1.mjs";
import { normalizePiloteContinuationAliasV1, compileStrictLongrunNaturalLanguageFixtureV1, compileContinuationPolicyV1, compilePiloteResponseGateV1, compileNewChatReattachSemanticsV1, compileIdentityPlanAutoContinueUxV1 } from "../pilote/rev52/continuation-response-gate-v1.mjs";
import { compileProviderNeutralJobIntentV1, consumeRuntimeCapabilityDecisionV1, interpretExecutionSurfaceReattachV1, compileProviderEvidenceAcceptanceV1, consumeContentIdentityEvidenceReuseV1, acceptBillingResidueReceiptV1, compileAcceptanceDependencyGraphV1, evaluateAcceptanceDependencyGraphV1 } from "../pilote/rev52/provider-evidence-intent-v1.mjs";
import { compilePiloteDependentConformanceV1, evaluatePiloteDependentConformanceV1, PILOTE_REV52_REQUIRED_CONFORMANCE_GATES } from "../pilote/rev52/dependent-conformance-v1.mjs";

const handoff=JSON.parse(await readFile(new URL("../RUNTIME_REV52_HANDOFF_BUNDLE_V1.json",import.meta.url),"utf8"));
const freeze=JSON.parse(await readFile(new URL("../R52_RUNTIME_INTERFACE_FREEZE_v001.json",import.meta.url),"utf8"));
const seal=JSON.parse(await readFile(new URL("../R52_RUNTIME_DEVELOPMENT_SEAL_v001.json",import.meta.url),"utf8"));
const lock=JSON.parse(await readFile(new URL("../P52_RUNTIME_DEPENDENCY_LOCK_v001.json",import.meta.url),"utf8"));

test("D0 exact sealed Runtime handoff chain is accepted",()=>{const r=verifyRuntimeRev52HandoffV1({handoff,interfaceFreeze:freeze,developmentSeal:seal,expectedHandoffDigest:"eb122a65afc92d589b1af2eb923167cd47d144e1105669493b117249beefcbf8",expectedCarrierHead:"4256c95aa3521bf74c03c2e204a0b9a63d8626e0",expectedRuntimeSourceHead:"785ae47c1abc4363396b0805a2e43783132465bb",expectedRuntimeSourceTree:"487e701c880ecc49c5a95ba66f12b1cb2c6074fc",expectedInterfaceDigest:"d6b22817a194b864611118e36d19bb1fda0eeca6b8a60eda31bec82b5bf622c4"});assert.equal(r.ok,true,r.errors.join(","))});
test("D0 dependency lock is deterministic and immutable-runtime",()=>{assert.deepEqual(validatePiloteRuntimeDependencyLockV1(lock),{ok:true,errors:[]});assert.equal(lock.DEPENDENCY_LOCK_SHA256,"98d9e8f23c2b65c057f5300998255c21e5de9d31d788193a4755aa8d6aad7f02");assert.equal(lock.runtimeSourceMutationAllowed,false);assert.equal(lock.runtimeInterfaceRedefinitionAllowed,false);assert.equal(lock.runtimeInlinePatchAllowed,false);assert.equal(lock.providerSpecificImplementationAllowed,false)});

test("D1 plan graph and grant preserve Runtime decision authority",()=>{const p=compileAuthoritativePlanV1({dependencyLockSha256:lock.DEPENDENCY_LOCK_SHA256,planId:"pilote-track-b-v019",planDigest:"3e8583c1a5d875cfc54c1ae377ad6aba5385de500f3759f1f13cfa812c271ec9",phases:[{id:"D0",order:0,work:[{id:"bind",kind:"SPEC"}]},{id:"D1",order:1,dependsOn:["D0"],work:[{id:"compiler",kind:"CODE"}]},{id:"D2",order:2,dependsOn:["D1"],work:[{id:"auth",kind:"AUTH"}]},{id:"D3",order:3,dependsOn:["D2"],work:[{id:"response",kind:"CODE"}]},{id:"D4",order:4,dependsOn:["D3"],work:[{id:"provider",kind:"CODE"}]},{id:"D5",order:5,dependsOn:["D4"],work:[{id:"conformance",kind:"TEST"}]},{id:"D6",order:6,dependsOn:["D5"],work:[{id:"seal",kind:"SPEC"}]}]});const g=compileMasterPlanDependencyGraphV1(p);assert.deepEqual(g.phaseOrder,["D0","D1","D2","D3","D4","D5","D6"]);const grant=compileProjectRunGrantV1({grantId:"p52-track-b",dependencyLockSha256:lock.DEPENDENCY_LOCK_SHA256,planSha256:p.PILOTE_PLAN_SHA256,graphSha256:g.GRAPH_SHA256,developmentBranch:"pilote-r52-dependent",allowedPhaseIds:g.phaseOrder});const pg=compilePhaseExecutionGrantV1({projectRunGrantSha256:grant.PROJECT_RUN_GRANT_SHA256,phaseId:"D3",activeWorkIds:["response"]});assert.equal(pg.reapprovalOnPhaseTransition,false);assert.equal(grant.runtimeSourceMutationAllowed,false)});
test("D1 source-progress policy delegates NLA/auth eligibility to Runtime",()=>{const p=compileSourceProgressPolicyV1({projectRunGrantSha256:"1".repeat(64)});assert.equal(p.runtimeResolverAuthority,"RUNTIME_NEXT_LEGAL_ACTION_RESOLVER");assert.equal(p.runtimeAuthEligibilityAuthority,"RUNTIME_AUTH_ENDGAME_ELIGIBILITY");assert.equal(p.currentPhaseExhaustionMeansProjectExhaustion,false);assert.equal(compileExplicitDependencyV1({type:"SEMANTIC",actionId:"live"}).blocksSourceProgress,true);assert.equal(compileExplicitDependencyV1({type:"ADMINISTRATIVE",actionId:"live"}).blocksSourceProgress,false);const i=interpretRuntimeProjectRunStateV2V1({runtimeState:{SCHEMA_ID:"PROJECT_RUN_STATE_V2",ACTIVE_NEXT:{id:"later"},DEFERRED_AUTH_NEXT:{id:"auth"},DEFERRED_PROVIDER_LIVE_WORK:[],DEFERRED_PAID_RESOURCE_WORK:[],DEFERRED_FINAL_MERGE_RELEASE_WORK:[]},sourceProgressPolicy:p});assert.equal(i.authEligibilityDecisionMadeByPilote,false)});

test("D2 auth collector deduplicates and final policy is auth-last",()=>{const s=collectAuthRequirementsV1([{provider:"github",capability:"actions:read",scope:"repo"},{provider:"github",capability:"actions:read",scope:"repo"}]);assert.equal(s.requirements.length,1);const p=compileFinalAuthBindPolicyV1({authRequirementSetSha256:s.AUTH_REQUIREMENT_SET_SHA256});assert.equal(p.authLast,true);assert.equal(p.interactivePromptMaxPerProjectRun,1);assert.equal(p.runtimeAuthEligibilityAuthority,"RUNTIME")});
test("D2 Runtime owns eligibility and mutation envelope evaluation",()=>{const a=compileRuntimeAuthEligibilityRequestV1({projectIdentityDigest:"2".repeat(64),sourceManifestDigest:"3".repeat(64),projectRunStateSha256:"4".repeat(64),authRequirementSetSha256:"5".repeat(64)});assert.equal(a.piloteDoesNotDecideEligibility,true);const m=compileSourceMutationAuthorityRequestV1({projectIdentityDigest:"2".repeat(64),authoritativePlanSetDigest:"6".repeat(64),targetRepository:"neoflowcore/atelier-runtime",developmentBranchOrBranchClass:"pilote-r52-dependent",authoritySource:"CURRENT_PROJECT_USER"});assert.equal(m.runtimeEvaluationRequired,true);assert.equal(compileAuthorityBoundaryV1({boundaryType:"NEW_SECRET_AUTHORITY"}).userApprovalRequired,true);assert.equal(compileAuthorityBoundaryV1({boundaryType:"WORK_UNIT_CHANGE"}).userApprovalRequired,false);const lp=compileLeastPrivilegeStagingV1({requirements:[{provider:"github",capability:"actions:read",scope:"repo"}]});assert.equal(lp.staged[0].bindTiming,"AUTH_ENDGAME_ONLY");assert.equal(lp.staged[0].materializedSecretAllowed,false)});

test("D3 aliases bind to existing run only",()=>{assert.equal(normalizePiloteContinuationAliasV1("ㅇㅇ").matched,true);assert.equal(normalizePiloteContinuationAliasV1("DD").matched,true);const f=compileStrictLongrunNaturalLanguageFixtureV1();assert.equal(f.runtimeParserRequirement,false);assert.ok(f.deniedInterpretations.includes("grant final merge authority"))});
test("D3 response gate stays closed on continuation and opens only on boundary",()=>{const p=compileContinuationPolicyV1({projectRunGrantSha256:"7".repeat(64)});assert.equal(p.phaseCompleteIsStop,false);assert.equal(p.ciPassIsStop,false);assert.equal(p.identityVerifiedIsStop,false);const c=compilePiloteResponseGateV1({runtimeDecision:{decision:"CONTINUE_CREDENTIAL_INDEPENDENT_WORK"}});assert.equal(c.continueExecution,true);assert.equal(c.finalResponseAllowed,false);const b=compilePiloteResponseGateV1({runtimeDecision:{decision:"PLATFORM_APPROVAL_REQUIRED"}});assert.equal(b.finalResponseAllowed,true)});
test("D3 reattach does not reset approval/auth/phase and identity+plan verification auto-continues",()=>{const r=compileNewChatReattachSemanticsV1({projectIdentityMatched:true,planMatched:true,runtimeDependencyLockMatched:true});assert.equal(r.decision,"REATTACH_EXISTING_PILOTE_RUN");assert.equal(r.duplicateExecutionAllowed,false);assert.equal(r.approvalReset,false);assert.equal(r.authReset,false);const ux=compileIdentityPlanAutoContinueUxV1({identityVerified:true,planVerified:true});assert.equal(ux.autoContinue,true);assert.equal(ux.confirmationPromptRequired,false)});

test("D4 provider intent is neutral and Runtime selects provider",()=>{const i=compileProviderNeutralJobIntentV1({jobId:"j",executionClass:"HOSTED",requiredCapabilities:["PROCESS_EXEC"],runtimeCapabilityContractSha256:"8".repeat(64)});assert.equal(i.providerSpecificLogic,false);assert.equal(i.providerSelectionAuthority,"RUNTIME_PROVIDER_CONTROL_LAYER");assert.throws(()=>compileProviderNeutralJobIntentV1({jobId:"j",executionClass:"HOSTED",requiredCapabilities:["PROCESS_EXEC"],runtimeCapabilityContractSha256:"8".repeat(64),github:{workflow:"x"}}),/PROVIDER_SPECIFIC_LOGIC_DENIED/)});
test("D4 consumes Runtime capability/surface/evidence/reuse/billing decisions",()=>{assert.equal(consumeRuntimeCapabilityDecisionV1({decision:"ADMIT",providerId:"p"}).piloteCapabilityResolutionPerformed,false);const s=interpretExecutionSurfaceReattachV1({decision:"HOT_REATTACH",surface:{id:"x"}});assert.equal(s.reattach,true);assert.equal(s.reaskConnection,false);assert.equal(compileProviderEvidenceAcceptanceV1({evidenceId:"e",runtimeEvidenceDigest:"9".repeat(64),runtimeEvidenceStatus:"PASS",runtimeInvalidationStatus:"VALID"}).accepted,true);assert.equal(consumeContentIdentityEvidenceReuseV1({reusable:true}).accepted,true);assert.equal(acceptBillingResidueReceiptV1({SCHEMA_ID:"BILLING_RESIDUE_RECEIPT_V3",status:"PASS",activePaidCompute:0,orphanedBillableResource:0,billableResidue:0,deleteOrTerminateReadback:true,childBillableArtifactsScanned:true}).accepted,true)});
test("D4 acceptance dependency graph is fail-closed",()=>{const g=compileAcceptanceDependencyGraphV1([{id:"runtime",status:"PASS"},{id:"provider",status:"PASS",dependsOn:["runtime"]},{id:"final",status:"PASS",dependsOn:["provider"]}]);assert.equal(evaluateAcceptanceDependencyGraphV1(g).status,"PASS");const b=compileAcceptanceDependencyGraphV1([{id:"runtime",status:"PASS"},{id:"provider",status:"PENDING",dependsOn:["runtime"]},{id:"final",status:"PASS",dependsOn:["provider"]}]);assert.equal(evaluateAcceptanceDependencyGraphV1(b).status,"BLOCKED")});

test("D5 full dependent compatibility matrix passes with zero Runtime mutation/provider-specific logic",()=>{const r=compilePiloteDependentConformanceV1({runtimeDependencyLockSha256:lock.DEPENDENCY_LOCK_SHA256,runtimeHandoffDigest:lock.runtimeHandoffDigest,runtimeInterfaceDigest:lock.runtimeInterfaceDigest,checks:PILOTE_REV52_REQUIRED_CONFORMANCE_GATES.map(id=>({id,status:"PASS",evidenceRef:`test:${id}`})),runtimeSourceMutationCount:0,providerSpecificLogicCount:0});const e=evaluatePiloteDependentConformanceV1(r);assert.equal(e.pass,true);assert.equal(e.runtimeSourceMutationCount,0);assert.equal(e.providerSpecificLogicCount,0)});
test("D5 missing gate or Runtime mutation fails dependent qualification",()=>{const r=compilePiloteDependentConformanceV1({runtimeDependencyLockSha256:lock.DEPENDENCY_LOCK_SHA256,runtimeHandoffDigest:lock.runtimeHandoffDigest,runtimeInterfaceDigest:lock.runtimeInterfaceDigest,checks:PILOTE_REV52_REQUIRED_CONFORMANCE_GATES.slice(1).map(id=>({id,status:"PASS"})),runtimeSourceMutationCount:1,providerSpecificLogicCount:0});assert.equal(evaluatePiloteDependentConformanceV1(r).pass,false)});
