import test from "node:test";import assert from "node:assert/strict";import{createEphemeralValidationRefLeaseV1,createGeneratedSourceArtifactProvenanceV1,evaluateSourcePromotionEligibilityV1,buildSourcePromotionReceiptV1}from"../runtime/rev51/validation-source-promotion-v1.mjs";const H=x=>x.repeat(64),T="2026-09-27T00:00:00.000Z",T2="2026-09-27T01:00:00.000Z";const p=(o={})=>createGeneratedSourceArtifactProvenanceV1({INPUT_SOURCE_SHA:"a",INPUT_TREE_SHA:"b",ARTIFACT_PATH:"package-lock.json",ARTIFACT_SHA256:H("a"),ENVIRONMENT_FINGERPRINT_SHA256:H("b"),PACKAGE_MANAGER_VERSION:"10.9.2",REGISTRY_PROFILE_SHA256:H("c"),DEPENDENCY_RESOLUTION_POLICY_SHA256:H("d"),TRACE_ID:"t",JOB_ID:"j",CANONICAL_VALIDATION_STATUS:"PASS",...o});
test("P11 validation ref must stay in runtime validation namespace",()=>assert.throws(()=>createEphemeralValidationRefLeaseV1({JOB_ID:"j",REF_NAME:"main",CANDIDATE_SHA:"a",CREATED_AT:T,DELETE_AFTER:T2,CLEANUP_AUTHORITY_READY:true}),/NAMESPACE_INVALID|DENIED/));
test("P11 validation ref requires cleanup authority",()=>assert.throws(()=>createEphemeralValidationRefLeaseV1({JOB_ID:"j",REF_NAME:"runtime/validation/j",CANDIDATE_SHA:"a",CREATED_AT:T,DELETE_AFTER:T2,CLEANUP_AUTHORITY_READY:false}),/CLEANUP_AUTHORITY_REQUIRED/));
test("P11 generated source provenance binds exact inputs and validation",()=>assert.match(p().PROVENANCE_SHA256,/^[0-9a-f]{64}$/));
test("P11 promotion requires canonical validation PASS",()=>assert.equal(evaluateSourcePromotionEligibilityV1({provenance:p({CANONICAL_VALIDATION_STATUS:"PENDING"}),freshHead:"a",freshTree:"b",sourceMutationAuthorized:true}).code,"CANONICAL_VALIDATION_REQUIRED"));
test("P11 fresh head tree drift forces mutation request recompile",()=>assert.equal(evaluateSourcePromotionEligibilityV1({provenance:p(),freshHead:"x",freshTree:"b",sourceMutationAuthorized:true}).code,"SOURCE_BASE_DRIFT_REQUIRES_RECOMPILE"));
test("P11 identical target content converges as SUCCESS_NOOP",()=>{const e=evaluateSourcePromotionEligibilityV1({provenance:p(),freshHead:"a",freshTree:"b",currentBlobSha256:H("a"),sourceMutationAuthorized:false});assert.equal(e.eligible,true);assert.equal(e.code,"SUCCESS_NOOP");assert.equal(e.mutationRequired,false)});
test("P11 source mutation requires explicit authority when content differs",()=>assert.equal(evaluateSourcePromotionEligibilityV1({provenance:p(),freshHead:"a",freshTree:"b",currentBlobSha256:H("e"),sourceMutationAuthorized:false}).code,"SOURCE_MUTATION_AUTHORITY_REQUIRED"));
test("P11 promotion receipt binds base and result identities",()=>{const prov=p();const e=evaluateSourcePromotionEligibilityV1({provenance:prov,freshHead:"a",freshTree:"b",currentBlobSha256:H("e"),sourceMutationAuthorized:true});const r=buildSourcePromotionReceiptV1({provenance:prov,eligibility:e,baseHead:"a",baseTree:"b",resultHead:"c",resultTree:"d",promotedBlobSha256:H("a")});assert.equal(r.OUTCOME,"SUCCESS_CHANGED");assert.match(r.RECEIPT_SHA256,/^[0-9a-f]{64}$/)});
