import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {A6_AUTHORITATIVE_BINDING,computeA6IntentSha256V1,deriveA6ParallelismProjectionV1,validateA6IntentV1,validateA6RuntimeBindingV1} from '../runtime/rev51/pilote-parallelism-execution-class-consumer-v1.mjs';
import {initializeDurableAdmissionBudgetV1} from '../runtime/rev51/durable-admission-budget-cancellation-v1.mjs';
const H1='1'.repeat(64),H2='2'.repeat(64),H3='3'.repeat(64),T0=Date.parse('2026-09-25T04:00:00.000Z');
function intent({p='INHERIT_DAG',m=4,c='RUNTIME_DEFAULT',d=['a']}={}){const q=deriveA6ParallelismProjectionV1(p,m);const v={INTENT_TYPE:'PILOTE_PARALLELISM_EXECUTION_CLASS_INTENT_V1',INTENT_VERSION:'1.0.0',CANONICALIZATION_ID:'ATELIER_EXECUTION_CANONICAL_JSON_V1',PROJECT_ID:'p',PHASE_ID:'ph',TASK_ID:'t',TASK_CONTRACT_SHA256:H1,EXECUTION_INTENT_SHA256:H2,EXECUTION_CLASS:c,EXECUTION_CLASS_SOURCE_REF:'task-contract:RESOURCE_REQUIREMENTS.EXECUTION_CLASS',PARALLELISM_INTENT:p,PARALLELISM_INTENT_SOURCE_REF:'execution-intent:PARALLELISM_INTENT',SEMANTIC_DEPENDENCY_REFS:d,SEMANTIC_DEPENDENCY_REFS_SOURCE_REF:'execution-intent:SEMANTIC_DEPENDENCY_REFS',MAX_PARALLELISM:m,MAX_PARALLELISM_SOURCE_REF:'task-contract:ECONOMY_BUDGET.MAX_PARALLELISM',EFFECTIVE_PARALLELISM_CAP:q.EFFECTIVE_PARALLELISM_CAP,PARALLEL_ALLOWED_POLICY:'PERMISSION_NOT_OBLIGATION',INHERIT_DAG_POLICY:'FOLLOW_SEMANTIC_DAG',SERIAL_REQUIRED_POLICY:'EFFECTIVE_CAP_ONE',RUNTIME_STRICTER_LIMIT:'ALLOW',RUNTIME_SEMANTIC_EDGE_ADD:'DENY',RUNTIME_SEMANTIC_EDGE_REMOVE:'DENY',RUNTIME_EXECUTION_ONLY_EDGE_ADD:'ALLOW',HARD_EXECUTION_CLASS_DOWNGRADE:'DENY',EXECUTION_CLASS_PROVIDER_SELECTION:'RUNTIME_OWNED',PROVIDER_TRANSPORT_INDEPENDENCE:'REQUIRED',ADMISSION_INTERSECTION_POLICY:'ALL_APPLICABLE_LIMITS_MUST_PASS',CONTRACT_SET_REF:{ID:'ATELIER_REV51_CONTRACT_SET_V1',VERSION:'1.0.0',SHA256:A6_AUTHORITATIVE_BINDING.CONTRACT_SET_SHA256},A6_INTENT_SHA256:'0'.repeat(64)};v.A6_INTENT_SHA256=computeA6IntentSha256V1(v);return v}
function plan(i){return{TASK_CONTRACT_SHA256:i.TASK_CONTRACT_SHA256,EXECUTION_INTENT_SHA256:i.EXECUTION_INTENT_SHA256,PARALLELISM_INTENT:i.PARALLELISM_INTENT,SEMANTIC_DEPENDENCY_REFS:[...i.SEMANTIC_DEPENDENCY_REFS]}}
function sel(r='HOSTED'){return{EXECUTION_CLASS_REALIZATION:r,COMPUTE_PROVIDER:'DIGITALOCEAN',EXECUTION_TRANSPORT:'DIRECT_WORKER',PROVIDER_SELECTION_SOURCE:'RUNTIME',TRANSPORT_SELECTION_SOURCE:'RUNTIME'}}
function lim(x={}){return{PROJECT_CONCURRENCY_LIMIT:8,PROVIDER_CONCURRENCY_LIMIT:8,EXECUTION_CLASS_LIMIT:8,REQUESTED_PARALLELISM:1,ACTIVE_COST_RESERVATION_REQUIRED:true,ACTIVE_COST_RESERVATION_AVAILABLE:true,...x}}
async function fx(i,b=i.MAX_PARALLELISM){const dir=await mkdtemp(join(tmpdir(),'a6-'));const store=await initializeDurableAdmissionBudgetV1(join(dir,'a.json'),{TASK_CONTRACT_SHA256:H1,EXECUTION_INTENT_SHA256:H2,EXECUTION_PLAN_SHA256:H3,ECONOMY_BUDGET:{MAX_EXECUTIONS:10,MAX_RETRIES:3,MAX_REPAIRS:3,MAX_PARALLELISM:b},BUDGET_INTENT:{MAX_RUNTIME_SECONDS:1000,MAX_COST_MICRO_USD:1000}},T0);return{dir,store}}
async function clean(f){await rm(f.dir,{recursive:true,force:true})}
function bind(i,f,over={}){return validateA6RuntimeBindingV1({a6Intent:i,runtimePlan:plan(i),admissionStore:f.store,runtimeLimits:lim(over.limits),selection:over.selection||sel(),semanticDependencyRefs:over.deps||i.SEMANTIC_DEPENDENCY_REFS,executionOnlyEdges:over.edges||[]})}
test('authoritative anchor pinned',()=>{assert.equal(A6_AUTHORITATIVE_BINDING.HEAD,'878e5966f6a4c3fc45f76659f83d107f17ce9f6d');assert.equal(A6_AUTHORITATIVE_BINDING.TREE,'e4eb4a8a1887fb859f0504431584f5f66869ce3b');assert.equal(A6_AUTHORITATIVE_BINDING.SCHEMA_SHA256,'f15d74050a35c56eb036deccd67f670953d2719082de2505f2881596e3bd2704');assert.equal(A6_AUTHORITATIVE_BINDING.AUTHORITATIVE_MANIFEST_SHA256,'29f7e31bafb295f3e6291ef30717dba080bb8a095cb4870c2ace9220ec94526a')});
test('serial cap one',async()=>{const i=intent({p:'SERIAL_REQUIRED',m:8});assert.deepEqual(validateA6IntentV1(i),{ok:true,errors:[]});const f=await fx(i);try{assert.equal(bind(i,f).projection.EFFECTIVE_PARALLELISM_CAP,1);assert.ok(bind(i,f,{limits:{REQUESTED_PARALLELISM:2}}).errors.includes('ADMISSION_PARALLELISM_INTERSECTION_DENIED'))}finally{await clean(f)}});
test('parallel allowed permission and stricter runtime limit',async()=>{const i=intent({p:'PARALLEL_ALLOWED',m:8});const f=await fx(i);try{const r=bind(i,f,{limits:{PROJECT_CONCURRENCY_LIMIT:3,REQUESTED_PARALLELISM:3},edges:['serialize:x']});assert.equal(r.ok,true);assert.equal(r.projection.A6_EFFECTIVE_PARALLELISM_CAP,8);assert.equal(r.projection.EFFECTIVE_PARALLELISM_CAP,3);assert.equal(r.projection.PARALLELISM_IS_PERMISSION_ONLY,true);assert.equal(r.projection.EXECUTION_ONLY_EDGE_COUNT,1)}finally{await clean(f)}});
test('semantic DAG preserved',async()=>{const i=intent({d:['a','b']});const f=await fx(i);try{assert.ok(bind(i,f,{deps:['b','a']}).errors.includes('SEMANTIC_DAG_PRESERVATION_MISMATCH'))}finally{await clean(f)}});
test('hard classes deny downgrade',async()=>{for(const [c,b,g] of [['SELF_HOSTED_REQUIRED','HOSTED','SELF_HOSTED'],['HOST_LOCAL_REQUIRED','SELF_HOSTED','HOST_LOCAL']]){const i=intent({c});const f=await fx(i);try{assert.ok(bind(i,f,{selection:sel(b)}).errors.includes('HARD_EXECUTION_CLASS_DOWNGRADE_DENIED'));assert.equal(bind(i,f,{selection:sel(g)}).ok,true)}finally{await clean(f)}}});
test('provider selection Runtime-owned',async()=>{const i=intent(),f=await fx(i);try{const s=sel();s.PROVIDER_SELECTION_SOURCE='PILOTE';assert.ok(bind(i,f,{selection:s}).errors.includes('PROVIDER_SELECTION_OWNERSHIP_MISMATCH'))}finally{await clean(f)}});
test('P2G max parallelism exact bind',async()=>{const i=intent({m:4}),f=await fx(i,3);try{assert.ok(bind(i,f).errors.includes('P2G_MAX_PARALLELISM_BINDING_MISMATCH'))}finally{await clean(f)}});
test('cost reservation intersects admission',async()=>{const i=intent(),f=await fx(i);try{assert.ok(bind(i,f,{limits:{ACTIVE_COST_RESERVATION_AVAILABLE:false}}).errors.includes('ACTIVE_COST_RESERVATION_REQUIRED'))}finally{await clean(f)}});
test('provider identity injection denied',()=>{const i=intent();i.PROVIDER_ID='DIGITALOCEAN';assert.ok(validateA6IntentV1(i).errors.some(x=>x.includes('FORBIDDEN_RUNTIME_OWNED_KEY')))});
