import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { initializeJobCredentialLeaseV1, readJobCredentialLeaseV1, validateJobCredentialUseV1, reconcileJobCredentialLeaseExpiryV1, requireJobCredentialRevocationV1, beginJobCredentialRevocationV1, recordJobCredentialRevocationOutcomeV1 } from "../harness/runtime/rev51/durable-job-credential-lease-v1.mjs";
const H="a".repeat(64),J="b".repeat(64),A="c".repeat(64);
const T0=Date.parse("2026-09-24T00:00:00.000Z"),T1=T0+60000;
function init(extra={}){return{CREDENTIAL_LEASE_ID:"lease-1",EXECUTION_ID:"exec-1",ATTEMPT_ID:"attempt-1",FENCE_TOKEN:"fence-1",WORKER_ID:"worker-1",WORKER_JOB_SHA256:J,WORKER_READY_ATTESTATION_HASH:A,CREDENTIAL_REF:"cred-ref-1",AUTHORITY_EVIDENCE_SHA256:H,LEASE_SCOPE:"JOB_SCOPED",WORKER_ATTESTED:true,PRIVILEGED_JOB_CREDENTIAL_PRESENT:true,EXPIRES_AT_MS:T1,...extra}}
async function fx(){const d=await mkdtemp(join(tmpdir(),"p2k-"));return{d,p:join(d,"lease.json")}}
async function withFx(fn){const f=await fx();try{await fn(f)}finally{await rm(f.d,{recursive:true,force:true})}}
const use=(s={})=>({EXECUTION_ID:"exec-1",ATTEMPT_ID:"attempt-1",FENCE_TOKEN:"fence-1",WORKER_ID:"worker-1",WORKER_JOB_SHA256:J,WORKER_READY_ATTESTATION_HASH:A,...s});
test("init active job-scoped lease",()=>withFx(async f=>{const s=await initializeJobCredentialLeaseV1(f.p,init(),T0);assert.equal(s.LEASE_STATUS,"ACTIVE");assert.equal(s.SECRET_PERSISTED,false)}));
test("unattested privileged credential denied",()=>withFx(async f=>{await assert.rejects(()=>initializeJobCredentialLeaseV1(f.p,init({WORKER_ATTESTED:false}),T0),/UNATTESTED/)}));
test("secret material field denied",()=>withFx(async f=>{await assert.rejects(()=>initializeJobCredentialLeaseV1(f.p,{...init(),SECRET_VALUE:"x"},T0),/SECRET_MATERIAL/)}));
test("wrong scope denied",()=>withFx(async f=>{await assert.rejects(()=>initializeJobCredentialLeaseV1(f.p,init({LEASE_SCOPE:"GLOBAL"}),T0),/JOB_SCOPED/)}));
test("current binding allows use",()=>withFx(async f=>{const s=await initializeJobCredentialLeaseV1(f.p,init(),T0);assert.deepEqual(validateJobCredentialUseV1(s,use(),T0+1),{ok:true,code:"JOB_CREDENTIAL_USE_ALLOWED"})}));
test("stale fence denied",()=>withFx(async f=>{const s=await initializeJobCredentialLeaseV1(f.p,init(),T0);assert.equal(validateJobCredentialUseV1(s,use({FENCE_TOKEN:"old"}),T0+1).code,"STALE_FENCE_REJECTED")}));
test("wrong worker job denied",()=>withFx(async f=>{const s=await initializeJobCredentialLeaseV1(f.p,init(),T0);assert.equal(validateJobCredentialUseV1(s,use({WORKER_JOB_SHA256:H}),T0+1).code,"LEASE_WORKER_JOB_BINDING_MISMATCH")}));
test("expiry closes use and requires revocation",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);const r=await reconcileJobCredentialLeaseExpiryV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"exp-1",RUNTIME_NOW_MS:T1});assert.equal(r.state.LEASE_STATUS,"EXPIRED");assert.equal(r.state.REVOCATION_STATE,"REQUIRED");assert.equal(validateJobCredentialUseV1(r.state,use(),T1).ok,false)}));
test("terminal request requires revocation before expiry",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);const r=await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1,REASON:"CANCELLED"});assert.equal(r.state.REVOCATION_STATE,"REQUIRED")}));
test("revocation outcome unknown blocks different operation",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1});await beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:1,IDEMPOTENCY_KEY:"begin-1",RUNTIME_NOW_MS:T0+2,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1"});await recordJobCredentialRevocationOutcomeV1(f.p,{EXPECTED_STATE_VERSION:2,IDEMPOTENCY_KEY:"out-1",RUNTIME_NOW_MS:T0+3,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1",RESULT:"OUTCOME_UNKNOWN"});await assert.rejects(()=>beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:3,IDEMPOTENCY_KEY:"begin-2",RUNTIME_NOW_MS:T0+4,OPERATION_ID:"op-2",OPERATION_IDEMPOTENCY_KEY:"remote-2"}),/SECOND_MUTATION_DENIED/)}));
test("same revocation operation may reconcile to pass",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1});await beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:1,IDEMPOTENCY_KEY:"begin-1",RUNTIME_NOW_MS:T0+2,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1"});await recordJobCredentialRevocationOutcomeV1(f.p,{EXPECTED_STATE_VERSION:2,IDEMPOTENCY_KEY:"out-1",RUNTIME_NOW_MS:T0+3,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1",RESULT:"OUTCOME_UNKNOWN"});await beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:3,IDEMPOTENCY_KEY:"reconcile-begin",RUNTIME_NOW_MS:T0+4,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1"});const r=await recordJobCredentialRevocationOutcomeV1(f.p,{EXPECTED_STATE_VERSION:4,IDEMPOTENCY_KEY:"reconcile-out",RUNTIME_NOW_MS:T0+5,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1",RESULT:"PASS"});assert.equal(r.state.LEASE_STATUS,"REVOKED");assert.equal(r.state.REVOCATION_STATE,"REVOKED")}));
test("idempotent exact replay",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);const q={EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1,REASON:"CANCELLED"};const a=await requireJobCredentialRevocationV1(f.p,q),b=await requireJobCredentialRevocationV1(f.p,{...q,RUNTIME_NOW_MS:T0+99});assert.equal(a.state.STATE_VERSION,1);assert.equal(b.replay,true);assert.equal(b.state.STATE_VERSION,1)}));
test("idempotency conflict denied",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1,REASON:"CANCELLED"});await assert.rejects(()=>requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+2,REASON:"TRUST_RESET"}),/IDEMPOTENCY_KEY_CONFLICT/)}));
test("crash reopen preserves revoked state",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1});await beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:1,IDEMPOTENCY_KEY:"begin-1",RUNTIME_NOW_MS:T0+2,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1"});await recordJobCredentialRevocationOutcomeV1(f.p,{EXPECTED_STATE_VERSION:2,IDEMPOTENCY_KEY:"out-1",RUNTIME_NOW_MS:T0+3,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1",RESULT:"PASS"});const s=await readJobCredentialLeaseV1(f.p);assert.equal(s.LEASE_STATUS,"REVOKED")}));

test("revocation required immediately blocks credential use",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);const r=await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1,REASON:"CANCELLED"});assert.equal(validateJobCredentialUseV1(r.state,use(),T0+2).code,"CREDENTIAL_LEASE_REVOCATION_PENDING")}));
test("outcome unknown same operation id but different remote idempotency denied",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-1",RUNTIME_NOW_MS:T0+1,REASON:"TERMINAL"});await beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:1,IDEMPOTENCY_KEY:"begin-1",RUNTIME_NOW_MS:T0+2,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1"});await recordJobCredentialRevocationOutcomeV1(f.p,{EXPECTED_STATE_VERSION:2,IDEMPOTENCY_KEY:"out-1",RUNTIME_NOW_MS:T0+3,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-1",RESULT:"OUTCOME_UNKNOWN"});await assert.rejects(()=>beginJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:3,IDEMPOTENCY_KEY:"begin-2",RUNTIME_NOW_MS:T0+4,OPERATION_ID:"op-1",OPERATION_IDEMPOTENCY_KEY:"remote-2"}),/SECOND_MUTATION_DENIED/)}));
test("arbitrary revocation reason denied",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);await assert.rejects(()=>requireJobCredentialRevocationV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"req-x",RUNTIME_NOW_MS:T0+1,REASON:"secret text"}),/REVOCATION_REASON_INVALID/)}));

test("tampered event rejected",()=>withFx(async f=>{await initializeJobCredentialLeaseV1(f.p,init(),T0);const raw=JSON.parse(await readFile(f.p,"utf8"));raw.EVENT_LEDGER[0].EVENT_SHA256="0".repeat(64);await writeFile(f.p,JSON.stringify(raw));await assert.rejects(()=>readJobCredentialLeaseV1(f.p),/LEASE_EVENT_HASH_MISMATCH/)}));
