import test from "node:test";import assert from "node:assert/strict";import{createProviderExecutionAdapterReadinessV1,planFallbackExecutionV1}from"../runtime/rev51/provider-execution-adapter-readiness-v1.mjs";const T=Date.parse("2026-09-27T00:00:00Z"),H=x=>x.repeat(64);const r=(o={})=>createProviderExecutionAdapterReadinessV1({PROVIDER_ID:"gh",STATE:"READY",CONTROL_PLANE_AUTHORITY_READY:true,EXACT_SHA_CHECKOUT_READY:true,SOURCE_BUNDLE_IMPORT_READY:true,EPHEMERAL_REF_CHECKOUT_READY:true,ARTIFACT_RETURN_READY:true,WORKFLOW_DISPATCH_READY:true,CLEANUP_READY:true,VALIDATION_HARNESS_SHA256:H("a"),OBSERVED_AT:new Date(T).toISOString(),VALID_UNTIL:new Date(T+60000).toISOString(),...o});
test("P10 READY adapter requires artifact cleanup and some source transport",()=>assert.throws(()=>r({EXACT_SHA_CHECKOUT_READY:false,SOURCE_BUNDLE_IMPORT_READY:false,EPHEMERAL_REF_CHECKOUT_READY:false}),/READY_ADAPTER_REQUIRED_CAPABILITY_MISSING/));
test("P10 exact SHA checkout is preferred transport",()=>{const x=planFallbackExecutionV1({readiness:r(),runtimeNowMs:T+1,candidateSha:"abc",sourceBundleSha256:H("b"),remoteFullRunBudget:1,ephemeralRefAllowed:true});assert.equal(x.ok,true);assert.equal(x.plan.SOURCE_TRANSPORT,"EXACT_SHA_CHECKOUT")});
test("P10 immutable source bundle is second priority",()=>{const x=planFallbackExecutionV1({readiness:r({EXACT_SHA_CHECKOUT_READY:false}),runtimeNowMs:T+1,candidateSha:"abc",sourceBundleSha256:H("b"),remoteFullRunBudget:1,ephemeralRefAllowed:true});assert.equal(x.plan.SOURCE_TRANSPORT,"IMMUTABLE_SOURCE_BUNDLE")});
test("P10 ephemeral validation ref is last source transport",()=>{const x=planFallbackExecutionV1({readiness:r({EXACT_SHA_CHECKOUT_READY:false,SOURCE_BUNDLE_IMPORT_READY:false}),runtimeNowMs:T+1,candidateSha:"abc",remoteFullRunBudget:1,ephemeralRefAllowed:true});assert.equal(x.plan.SOURCE_TRANSPORT,"EPHEMERAL_VALIDATION_REF")});
test("P10 stale readiness fails closed",()=>assert.equal(planFallbackExecutionV1({readiness:r(),runtimeNowMs:T+60000,candidateSha:"abc",remoteFullRunBudget:1}).code,"ADAPTER_READINESS_STALE"));
test("P10 exact candidate remote full-run budget is one",()=>assert.throws(()=>planFallbackExecutionV1({readiness:r(),runtimeNowMs:T+1,candidateSha:"abc",remoteFullRunBudget:2}),/MUST_EQUAL_ONE/));
test("P10 fallback denies intermediate remote gate and matrix expansion",()=>{const x=planFallbackExecutionV1({readiness:r(),runtimeNowMs:T+1,candidateSha:"abc",remoteFullRunBudget:1});assert.equal(x.plan.INTERMEDIATE_REMOTE_GATE_ALLOWED,false);assert.equal(x.plan.MATRIX_EXPANSION_ALLOWED,false)});
test("P10 bootstrap-required provider is not ready to run",()=>assert.equal(planFallbackExecutionV1({readiness:r({STATE:"BOOTSTRAP_REQUIRED"}),runtimeNowMs:T+1,candidateSha:"abc",remoteFullRunBudget:1}).code,"EXECUTION_ADAPTER_NOT_READY"));
