import test from "node:test";import assert from "node:assert/strict";
import {createProviderNeutralReferenceAdapterV1,compileRepositoryCiSourceIdentityFixtureV1} from "../runtime/rev52/provider-reference-adapter-v1.mjs";
import {compileLongrunConformanceFixtureSetV1,evaluateLongrunConformanceV1,REQUIRED_SCENARIOS} from "../runtime/rev52/longrun-conformance-v1.mjs";

test("R7 reference adapter exposes provider-neutral discover/read/diff/mutate/readback/cleanup/residue flow",()=>{const a=createProviderNeutralReferenceAdapterV1({initialState:{enabled:false}});assert.equal(a.discover().providerId,"reference");assert.equal(a.diffDesired({enabled:true}).equal,false);assert.equal(a.mutateMinimalDelta({operationId:"op-1",desiredState:{enabled:true}}).status,"SUCCESS_CHANGED");assert.deepEqual(a.authoritativeReadback().state,{enabled:true});assert.equal(a.cleanup().status,"SUCCESS_NOOP");assert.equal(a.residueScan().billableResidue,0)});
test("R7 reference adapter is idempotent and current==desired is no-op",()=>{const a=createProviderNeutralReferenceAdapterV1({initialState:{enabled:true}});assert.equal(a.mutateMinimalDelta({operationId:"op-1",desiredState:{enabled:true}}).status,"SUCCESS_NOOP");const one=a.mutateMinimalDelta({operationId:"op-2",desiredState:{enabled:false}}),two=a.mutateMinimalDelta({operationId:"op-2",desiredState:{enabled:false}});assert.equal(one.status,"SUCCESS_CHANGED");assert.equal(two.status,"REPLAY");assert.equal(two.mutationCount,1)});
test("R7 repository CI identity fixture separates workflow existence, dispatchability and run creation",()=>{const f=compileRepositoryCiSourceIdentityFixtureV1({repository:"neoflowcore/atelier-runtime",head:"a".repeat(40),tree:"b".repeat(40),workflowTriggerRegistered:true,workflowDispatchable:false,runCreationObserved:false});assert.equal(f.workflowTriggerRegistered,true);assert.equal(f.workflowDispatchable,false);assert.equal(f.runCreationObserved,false)});
test("R8 exact required long-run fixture set passes with zero intervention KPIs",()=>{const set=compileLongrunConformanceFixtureSetV1(REQUIRED_SCENARIOS.map(s=>({scenario:s,result:"PASS",metrics:{}})));const r=evaluateLongrunConformanceV1(set);assert.equal(r.status,"PASS");for(const v of Object.values(r.metrics))assert.equal(v,0)});
test("R8 missing fixture fails closed",()=>{const set=compileLongrunConformanceFixtureSetV1(REQUIRED_SCENARIOS.slice(1).map(s=>({scenario:s,result:"PASS"})));assert.equal(evaluateLongrunConformanceV1(set).status,"FAIL")});
test("R8 premature stop/auth/reconnect/billing residue metrics fail qualification",()=>{const fixtures=REQUIRED_SCENARIOS.map(s=>({scenario:s,result:"PASS",metrics:{}}));fixtures[0].metrics={PREMATURE_STOP:1};const r=evaluateLongrunConformanceV1(compileLongrunConformanceFixtureSetV1(fixtures));assert.equal(r.status,"FAIL");assert.equal(r.metrics.PREMATURE_STOP,1)});
