import test from "node:test";import assert from "node:assert/strict";
import{compileProviderSchedulingPolicyV1,createProviderCircuitBreakerV1,recordProviderOutcomeV1,selectProviderDeterministicallyV1,executionStartReattestationV1}from"../runtime/rev51/provider-scheduler-safe-fallback-v1.mjs";
import{createProviderCapabilityProfileV1}from"../runtime/rev51/provider-capability-registry-v1.mjs";import{compileExactRuntimeProvisioningPlanV1}from"../runtime/rev51/exact-runtime-provisioner-v1.mjs";
const T=Date.parse("2026-09-27T00:00:00Z"),H=x=>x.repeat(64),V=H("a");
const req={REQUIRED_CAPABILITIES_SHA256:H("b"),EXECUTION_ENVIRONMENT_CONTRACT_SHA256:H("c"),REQUIRED_CAPABILITIES:["PROCESS_EXEC"],TASK_CAPABILITIES:["PROCESS_EXEC"],OS_CLASS:"LINUX",ARCH_CLASS:"X64",WORKSPACE_CLASS:"READ_ONLY",NETWORK_CLASS:"ALLOWLIST_READ",DATA_ACCESS_CLASS:"PROJECT_INTERNAL",SECRET_CLASS:"NONE",LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.13.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",LIBC_CLASS:"GLIBC",CONTAINER_IMAGE_DIGEST:null,REGISTRIES:[],MIN_DISK_MIB:0,MIN_MEMORY_MIB:0};
function p(id){return createProviderCapabilityProfileV1({PROVIDER_ID:id,EXECUTION_ADAPTER_STATE:"READY",HEALTH_STATE:"HEALTHY",COST_CLASS:"FREE",CAPABILITIES:["PROCESS_EXEC"],OS_CLASSES:["LINUX"],ARCH_CLASSES:["X64"],WORKSPACE_CLASSES:["READ_ONLY"],NETWORK_CLASSES:["ALLOWLIST_READ"],DATA_ACCESS_CLASSES:["PROJECT_INTERNAL"],SECRET_CLASSES:["NONE"],RUNTIME_FINGERPRINTS:["NODE@22.13.0"],PACKAGE_MANAGER_FINGERPRINTS:["NPM@10.9.2"],REGISTRIES:[],AVAILABLE_DISK_MIB:4096,AVAILABLE_MEMORY_MIB:4096,OBSERVED_AT:new Date(T).toISOString(),VALID_UNTIL:new Date(T+60000).toISOString()})}
function registry(){const a=p("a"),b=p("b");return{SCHEMA_ID:"PROVIDER_CAPABILITY_REGISTRY_V1",SCHEMA_VERSION:"1",REGISTRY_ID:"r",STATE_VERSION:1,PROFILES:{a,b},IDEMPOTENCY_INDEX:{},CREATED_AT:new Date(T).toISOString(),UPDATED_AT:new Date(T).toISOString()}}
const facts={a:{EXECUTION_ZONES:["KR"],DATA_CLASSIFICATIONS:["PROJECT_INTERNAL"],EXTERNAL_UPLOAD_CAPABLE:false,SOURCE_EGRESS_REQUIRED:false,ARTIFACT_EGRESS_REQUIRED:false},b:{EXECUTION_ZONES:["US"],DATA_CLASSIFICATIONS:["PUBLIC"],EXTERNAL_UPLOAD_CAPABLE:false,SOURCE_EGRESS_REQUIRED:false,ARTIFACT_EGRESS_REQUIRED:false}};
function backend(id){return{BACKEND_ID:id,ROUTER_PRIORITY:1,EXECUTION_CLASS_REALIZATION:"HOSTED",CAPABILITIES:["PROCESS_EXEC"],VERIFIER_POLICY_SHA256S:[V],READY:true,EXECUTION_TRANSPORT_READY:true}}
const policy=()=>compileProviderSchedulingPolicyV1({PROVIDER_ORDER:["a","b"],ALLOWED_COST_CLASSES:["FREE"],DATA_CLASSIFICATION:"PROJECT_INTERNAL",ALLOWED_EXECUTION_ZONES:["KR"],ALLOWED_PROVIDERS:["a","b"],EXTERNAL_UPLOAD_ALLOWED:false,SOURCE_EGRESS_ALLOWED:false,ARTIFACT_EGRESS_ALLOWED:false,INFRA_FAILURE_THRESHOLD:2});
test("P9 deterministic scheduling selects first fully eligible provider",()=>{const pol=policy(),r=selectProviderDeterministicallyV1({policy:pol,requiredCapabilities:req,registry:registry(),runtimeNowMs:T+1,backendCandidates:{a:backend("a"),b:backend("b")},providerPolicyFacts:facts,executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,circuitBreaker:createProviderCircuitBreakerV1(pol)});assert.equal(r.ok,true);assert.equal(r.selectedProviderId,"a")});
test("P9 data classification and zone are fail-closed gates",()=>{const pol=compileProviderSchedulingPolicyV1({PROVIDER_ORDER:["b"],ALLOWED_COST_CLASSES:["FREE"],DATA_CLASSIFICATION:"PROJECT_INTERNAL",ALLOWED_EXECUTION_ZONES:["KR"],ALLOWED_PROVIDERS:["b"],EXTERNAL_UPLOAD_ALLOWED:false,SOURCE_EGRESS_ALLOWED:false,ARTIFACT_EGRESS_ALLOWED:false});const r=selectProviderDeterministicallyV1({policy:pol,requiredCapabilities:req,registry:registry(),runtimeNowMs:T+1,backendCandidates:{b:backend("b")},providerPolicyFacts:facts,executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,circuitBreaker:createProviderCircuitBreakerV1(pol)});assert.equal(r.ok,false);assert.ok(r.evaluations[0].REASONS.includes("DATA_CLASSIFICATION_MISMATCH"));assert.ok(r.evaluations[0].REASONS.includes("EXECUTION_ZONE_MISMATCH"))});
test("P9 missing provider policy facts fail closed",()=>{const pol=policy(),r=selectProviderDeterministicallyV1({policy:pol,requiredCapabilities:req,registry:registry(),runtimeNowMs:T+1,backendCandidates:{a:backend("a")},providerPolicyFacts:{},executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,circuitBreaker:createProviderCircuitBreakerV1(pol)});assert.equal(r.ok,false);assert.ok(r.evaluations[0].REASONS.includes("DATA_CLASSIFICATION_MISMATCH"))});
test("P9 infrastructure failures quarantine provider at threshold",()=>{const pol=policy();let s=createProviderCircuitBreakerV1(pol);s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"INFRA_FAILURE"});assert.equal(s.QUARANTINED.length,0);s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"INFRA_FAILURE"});assert.deepEqual(s.QUARANTINED,["a"])});
test("P9 application failure never increments provider health failure count",()=>{const pol=policy();let s=createProviderCircuitBreakerV1(pol);s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"APPLICATION_FAILURE"});assert.equal(s.FAILURES.a??0,0);assert.equal(s.QUARANTINED.length,0)});
test("P9 health recheck restores quarantined provider",()=>{const pol=policy();let s=createProviderCircuitBreakerV1(pol);s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"INFRA_FAILURE"});s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"INFRA_FAILURE"});s=recordProviderOutcomeV1(s,pol,{providerId:"a",outcomeClass:"HEALTH_RECHECK_PASS"});assert.equal(s.QUARANTINED.length,0);assert.equal(s.FAILURES.a,0)});
test("P9 start reattestation composes P5 admission and P6 exact environment",()=>{const reg=registry(),pol=policy(),plan=compileExactRuntimeProvisioningPlanV1(req,reg.PROFILES.a);const r=executionStartReattestationV1({policy:pol,requiredCapabilities:req,registry:reg,providerId:"a",runtimeNowMs:T+1,backendCandidate:backend("a"),providerPolicyFacts:facts,executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,circuitBreaker:createProviderCircuitBreakerV1(pol),provisioningPlan:plan,environmentObservation:{PROVIDER_ID:"a",LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.13.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",OS_CLASS:"LINUX",ARCH_CLASS:"X64",LIBC_CLASS:"GLIBC",CONTAINER_IMAGE_DIGEST:null,PROVISIONER_POLICY_DIGEST:H("d")}});assert.equal(r.startAllowed,true);assert.match(r.receipt.RECEIPT_SHA256,/^[0-9a-f]{64}$/)});
test("P9 runtime drift blocks execution start",()=>{const reg=registry(),pol=policy(),plan=compileExactRuntimeProvisioningPlanV1(req,reg.PROFILES.a);const r=executionStartReattestationV1({policy:pol,requiredCapabilities:req,registry:reg,providerId:"a",runtimeNowMs:T+1,backendCandidate:backend("a"),providerPolicyFacts:facts,executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,circuitBreaker:createProviderCircuitBreakerV1(pol),provisioningPlan:plan,environmentObservation:{PROVIDER_ID:"a",LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.14.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",OS_CLASS:"LINUX",ARCH_CLASS:"X64",LIBC_CLASS:"GLIBC",CONTAINER_IMAGE_DIGEST:null,PROVISIONER_POLICY_DIGEST:H("d")}});assert.equal(r.startAllowed,false);assert.equal(r.code,"EXECUTION_ENVIRONMENT_DRIFT")});
