import test from "node:test";import assert from "node:assert/strict";import {readFile} from "node:fs/promises";
import {validateRuntimeRev52HandoffBundleV1} from "../runtime/rev52/development-seal-handoff-v1.mjs";
const seal=JSON.parse(await readFile(new URL("../R52_RUNTIME_DEVELOPMENT_SEAL_v001.json",import.meta.url),"utf8"));
const bundle=JSON.parse(await readFile(new URL("../RUNTIME_REV52_HANDOFF_BUNDLE_V1.json",import.meta.url),"utf8"));
test("R10 Development Seal closes every credential-independent Track A gate",()=>{for(const k of ["RUNTIME_CREDENTIAL_INDEPENDENT_TESTS","RUNTIME_LONGRUN_CONFORMANCE","RUNTIME_IDENTITY_PLAN_INPUT_CONTRACT","RUNTIME_SOURCE_PROGRESS_GATE","RUNTIME_AUTH_ENDGAME_ELIGIBILITY","RUNTIME_MUTATION_AUTHORITY","RUNTIME_PROVIDER_CONTROL","RUNTIME_HOT_REATTACH","RUNTIME_BILLING_RESIDUE_ZERO","RUNTIME_INTERFACE_FREEZE"])assert.equal(seal[k],"PASS",k);assert.equal(seal.RUNTIME_DEVELOPMENT_SEAL,"PASS")});
test("R10 seal deliberately excludes Pilote implementation and credential-bound final live acceptance",()=>{assert.equal(seal.PILOTE_IMPLEMENTATION_IN_RUNTIME_TRACK,false);assert.equal(seal.CREDENTIAL_BOUND_FINAL_LIVE_ACCEPTANCE_REQUIRED_FOR_SEAL,false)});
test("Runtime handoff is sealed, digest-valid, and terminal for Track A",()=>{assert.deepEqual(validateRuntimeRev52HandoffBundleV1(bundle),{ok:true,errors:[]});assert.equal(bundle.RUNTIME_HANDOFF_BUNDLE,"SEALED");assert.equal(bundle.RUNTIME_TRACK_ENDS_AT_HANDOFF,true);assert.equal(bundle.AUTO_ADVANCE_RUNTIME_TO_PILOTE,false)});
test("handoff pins Runtime 5.2 frozen interface and exact qualified source",()=>{assert.equal(bundle.runtimeInterfaceVersion,"5.2-FROZEN");assert.equal(bundle.runtimeInterfaceDigest,"d6b22817a194b864611118e36d19bb1fda0eeca6b8a60eda31bec82b5bf622c4");assert.equal(bundle.runtimeSourceIdentity.head,"785ae47c1abc4363396b0805a2e43783132465bb");assert.equal(bundle.runtimeSourceIdentity.tree,"487e701c880ecc49c5a95ba66f12b1cb2c6074fc")});
test("handoff contains all required Runtime contracts and canonical evidence refs",()=>{for(const n of ["ProjectRunStateV2","ProjectIdentityInput","ProjectSourceManifestInput","NextLegalActionResolver","AuthEndgameEligibility","ProviderControlAdapter","ExecutionSurface","MutationAuthorityEnvelope","BillingResidueReceipt","ContinuationDecision","EvidenceReceiptCompatibility"])assert.ok(bundle.contracts.includes(n),n);assert.ok(bundle.acceptanceEvidenceRefs.includes("github-actions:run:36400956342"));assert.ok(bundle.acceptanceEvidenceRefs.includes("github-actions:run:36401269805"))});
