import test from "node:test";import assert from "node:assert/strict";import{mkdtemp,rm,readFile,writeFile}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{initializeDurableReservationSettlementV1,readDurableReservationSettlementV1,settleReservationUsageV1,validateDurableReservationSettlementV1}from"../runtime/rev51/durable-reservation-settlement-v1.mjs";
const PLAN="a".repeat(64),T=Date.parse("2026-09-24T00:00:00Z");
const admission=(state="SUCCEEDED")=>({RESERVATIONS:{r1:{RESERVATION_ID:"r1",STATE:state,RUNTIME_SECONDS:100,COST_MICRO_USD:500,FENCE_TOKEN:"f1"}}});
async function fx(){const d=await mkdtemp(join(tmpdir(),"p2h-"));return{d,p:join(d,"s.json")}}
test("initialize/reopen",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);const s=await readDurableReservationSettlementV1(f.p);assert.equal(s.STATE_VERSION,0);assert.deepEqual(validateDurableReservationSettlementV1(s),{ok:true,errors:[]})}finally{await rm(f.d,{recursive:true,force:true})}});
test("settle actual usage and release unused",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);const r=await settleReservationUsageV1(f.p,admission(),{RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:70,ACTUAL_COST_MICRO_USD:350,EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1});assert.equal(r.settlement.RELEASED_RUNTIME_SECONDS,30);assert.equal(r.settlement.RELEASED_COST_MICRO_USD,150)}finally{await rm(f.d,{recursive:true,force:true})}});
for(const [name,req,re] of [["runtime overflow",{ACTUAL_RUNTIME_SECONDS:101,ACTUAL_COST_MICRO_USD:1},/ACTUAL_RUNTIME_EXCEEDS_RESERVATION/],["cost overflow",{ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:501},/ACTUAL_COST_EXCEEDS_RESERVATION/]])test(name,async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);await assert.rejects(settleReservationUsageV1(f.p,admission(),{RESERVATION_ID:"r1",EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1,...req}),re)}finally{await rm(f.d,{recursive:true,force:true})}});
test("nonterminal denied",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);await assert.rejects(settleReservationUsageV1(f.p,admission("STARTED"),{RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1}),/RESERVATION_NOT_TERMINAL/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("exact replay pass",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);const q={RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1};await settleReservationUsageV1(f.p,admission(),q);const r=await settleReservationUsageV1(f.p,admission(),{...q,RUNTIME_NOW_MS:T+2});assert.equal(r.replay,true)}finally{await rm(f.d,{recursive:true,force:true})}});
test("changed replay denied",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);const q={RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1};await settleReservationUsageV1(f.p,admission(),q);await assert.rejects(settleReservationUsageV1(f.p,admission(),{...q,ACTUAL_COST_MICRO_USD:2,RUNTIME_NOW_MS:T+2}),/SETTLEMENT_IDEMPOTENCY_CONFLICT/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("second settlement denied",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);await settleReservationUsageV1(f.p,admission(),{RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1});await assert.rejects(settleReservationUsageV1(f.p,admission(),{RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:1,IDEMPOTENCY_KEY:"k2",RUNTIME_NOW_MS:T+2}),/RESERVATION_ALREADY_SETTLED/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("cas mismatch denied",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);await assert.rejects(settleReservationUsageV1(f.p,admission(),{RESERVATION_ID:"r1",ACTUAL_RUNTIME_SECONDS:1,ACTUAL_COST_MICRO_USD:1,EXPECTED_STATE_VERSION:9,IDEMPOTENCY_KEY:"k1",RUNTIME_NOW_MS:T+1}),/SETTLEMENT_STATE_CAS_MISMATCH/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("tamper rejected",async()=>{const f=await fx();try{await initializeDurableReservationSettlementV1(f.p,{EXECUTION_PLAN_SHA256:PLAN},T);const x=JSON.parse(await readFile(f.p,"utf8"));x.EVENT_LEDGER[0].EVENT_SHA256="0".repeat(64);await writeFile(f.p,JSON.stringify(x));await assert.rejects(readDurableReservationSettlementV1(f.p),/SETTLEMENT_EVENT_HASH_MISMATCH/)}finally{await rm(f.d,{recursive:true,force:true})}});
