import test from "node:test";
import assert from "node:assert/strict";
import {compileProjectRunStateV2,migrateLegacyNextToProjectRunStateV2,validateProjectRunStateV2} from "../runtime/rev52/project-run-state-v2.mjs";
import {compileCredentialIndependentClosurePreflightV1,evaluateAuthEndgameEligibilityV1,resolveGlobalNextLegalActionV1,scanProjectWideCredentialIndependentWorkV1,validateExplicitLiveDependencyV1} from "../runtime/rev52/source-progress-resolver-v1.mjs";
const SHA="1".repeat(64);
function baseState(overrides={}){return{projectIdentityDigest:SHA,authoritativePlanSetDigest:"2".repeat(64),sourceManifestDigest:"3".repeat(64),runId:"runtime-r52-track-a",currentDevelopmentBranch:"runtime-r52-track-a",currentSourceIdentity:{repository:"neoflowcore/atelier-runtime",head:"8".repeat(40)},activePhaseId:"R52-R1",...overrides}}
test("ProjectRunStateV2 is deterministic and self-validating",()=>{const a=compileProjectRunStateV2(baseState()),b=compileProjectRunStateV2(baseState());assert.equal(a.PROJECT_RUN_STATE_SHA256,b.PROJECT_RUN_STATE_SHA256);assert.deepEqual(validateProjectRunStateV2(a),{ok:true,errors:[]})});
test("legacy NEXT=AUTH is deferred when later credential-independent work exists",()=>{const migrated=migrateLegacyNextToProjectRunStateV2({legacyState:{SCHEMA_ID:"LEGACY_PROJECT_RUN_STATE",NEXT:{id:"bind-auth",kind:"AUTH",phaseId:"R51-P30"}},baseState:baseState(),credentialIndependentActions:[{id:"r52-r1-state",kind:"CODE",phaseId:"R52-R1",order:1,status:"PENDING"},{id:"r52-r2-resolver",kind:"CODE",phaseId:"R52-R2",order:2,status:"PENDING"}]});assert.equal(migrated.state.ACTIVE_NEXT.id,"r52-r1-state");assert.equal(migrated.state.DEFERRED_AUTH_NEXT.id,"bind-auth");assert.equal(migrated.state.authEndgameState,"DEFERRED");assert.equal(migrated.receipt.legacyNextAuthOverrodeSource,false);assert.equal(migrated.receipt.duplicateExecutionAllowed,false)});
test("later source work remains active when current phase has only provider-live work",()=>{const actions=[{id:"r1-live",phaseId:"R52-R1",phaseOrder:1,kind:"PROVIDER_LIVE",status:"PENDING"},{id:"r2-code",phaseId:"R52-R2",phaseOrder:2,kind:"CODE",status:"PENDING"}];const scan=scanProjectWideCredentialIndependentWorkV1({actions}),next=resolveGlobalNextLegalActionV1({actions});assert.equal(scan.projectWideCredentialIndependentWorkExhausted,false);assert.deepEqual(scan.availableIds,["r2-code"]);assert.equal(next.ACTIVE_NEXT.id,"r2-code");assert.equal(next.authEndgameExecutable,false)});
test("administrative or inferred live dependency does not block source progress",()=>{assert.equal(validateExplicitLiveDependencyV1({type:"ADMINISTRATIVE",actionId:"live"}).blocksSourceProgress,false);const actions=[{id:"live",phaseId:"R52-R1",phaseOrder:1,kind:"PROVIDER_LIVE",status:"PENDING"},{id:"code",phaseId:"R52-R2",phaseOrder:2,kind:"CODE",status:"PENDING",liveDependency:{type:"ADMINISTRATIVE",actionId:"live"}}];assert.deepEqual(scanProjectWideCredentialIndependentWorkV1({actions}).availableIds,["code"])});
test("explicit semantic live dependency blocks only the affected source node",()=>{const actions=[{id:"live",phaseId:"R52-R1",phaseOrder:1,kind:"PROVIDER_LIVE",status:"PENDING"},{id:"affected",phaseId:"R52-R2",phaseOrder:2,kind:"CODE",status:"PENDING",liveDependency:{type:"SEMANTIC",actionId:"live"}},{id:"alternate",phaseId:"R52-R2",phaseOrder:2,order:2,kind:"TEST",status:"PENDING"}];const next=resolveGlobalNextLegalActionV1({actions});assert.equal(validateExplicitLiveDependencyV1({type:"SEMANTIC",actionId:"live"}).blocksSourceProgress,true);assert.equal(next.ACTIVE_NEXT.id,"alternate");assert.equal(next.localBlockerBypassed,true)});
test("auth endgame cannot execute while any credential-independent work remains",()=>{const actions=[{id:"auth",kind:"AUTH",status:"PENDING"},{id:"later-doc",phaseId:"R52-R3",phaseOrder:3,kind:"DOCS",status:"PENDING"}];const eligibility=evaluateAuthEndgameEligibilityV1({actions,closurePreflightPass:true});assert.equal(eligibility.AUTH_ENDGAME_READY,true);assert.equal(eligibility.AUTH_ENDGAME_EXECUTABLE,false)});
test("credential-independent closure preflight never requires auth, mutation, or paid compute",()=>{const preflight=compileCredentialIndependentClosurePreflightV1({actions:[]});assert.equal(preflight.decision,"PASS");assert.equal(preflight.requiresAuth,false);assert.equal(preflight.requiresProviderMutation,false);assert.equal(preflight.requiresPaidCompute,false)});
test("auth endgame becomes executable only after source exhaustion and closure PASS",()=>{const actions=[{id:"auth",kind:"AUTH",status:"PENDING"}];assert.equal(resolveGlobalNextLegalActionV1({actions,closurePreflightPass:false}).authEndgameExecutable,false);assert.equal(resolveGlobalNextLegalActionV1({actions,closurePreflightPass:true}).decision,"AUTH_ENDGAME_EXECUTABLE")});
