import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { computeTaskContractHash } from "../runtime/task-contract-v1.mjs";
import { compileExecutionEnvironmentContractV1, resolveRequiredCapabilitiesV1 } from "../runtime/rev51/capability-requirement-resolver-v1.mjs";
import { createProviderCapabilityProfileV1, initializeProviderCapabilityRegistryV1, upsertProviderCapabilityProfileV1, readProviderCapabilityRegistryV1, resolveCurrentProviderCapabilityProfileV1 } from "../runtime/rev51/provider-capability-registry-v1.mjs";
import { evaluateCapabilityAdmissionV1, buildCapabilityAdmissionReceiptV1 } from "../runtime/rev51/capability-admission-v1.mjs";
const T=Date.parse("2026-09-27T00:00:00Z"), V="a".repeat(64);
function task(){const t={TASK_ID:"t",PROJECT_ID:"p",PHASE_ID:"ph",TASK_CLASS:"VALIDATION",WORKLOAD_CLASS:"BUILD",SOURCE_IDENTITY:{KIND:"GIT",LOCATOR:"repo"},EXPECTED_HEAD:"0".repeat(40),EFFECT_CLASSES:["READ_ONLY"],ALLOWED_SCOPE:["repo:x"],TOUCH_SET:[],CAPABILITY_REQUIREMENTS:["NETWORK_EGRESS","PROCESS_EXEC","SOURCE_READ"],RESOURCE_REQUIREMENTS:{EXECUTION_CLASS:"HOSTED_ELIGIBLE",OS_CLASS:"LINUX",ARCH_CLASS:"X64",WORKSPACE_CLASS:"READ_ONLY"},NETWORK_CLASS:"ALLOWLIST_READ",DATA_ACCESS_CLASS:"PROJECT_INTERNAL",SECRET_CLASS:"NONE",REMOTE_MUTATION_INTENT:"NONE",HOST_OPERATION_INTENT:"NONE",ORACLE_REQUIREMENT:"NONE",ACCEPTANCE_REQUIREMENTS:[{ID:"a",TEXT:"a"}],VERIFIER_REQUIREMENTS:[{ID:"v",TEXT:"v"}],ECONOMY_BUDGET:{MAX_EXECUTIONS:1,MAX_RETRIES:0,MAX_REPAIRS:0,MAX_PARALLELISM:1},INTERVENTION_POLICY:"BLOCK",REPLAN_BOUNDARY:"TASK",EXPECTED_OUTPUTS:[],EXPECTED_EVIDENCE:[{ID:"e",TEXT:"e"}],CONTRACT_VERSION:"1.0.0"};t.TASK_CONTRACT_HASH=computeTaskContractHash(t);return t}
function profile(overrides={}){return createProviderCapabilityProfileV1({PROVIDER_ID:"provider-a",EXECUTION_ADAPTER_STATE:"READY",HEALTH_STATE:"HEALTHY",COST_CLASS:"FREE",CAPABILITIES:["NETWORK_EGRESS","PROCESS_EXEC","SOURCE_READ","REGISTRY_NPM"],OS_CLASSES:["LINUX"],ARCH_CLASSES:["X64"],WORKSPACE_CLASSES:["READ_ONLY"],NETWORK_CLASSES:["ALLOWLIST_READ"],DATA_ACCESS_CLASSES:["PROJECT_INTERNAL"],SECRET_CLASSES:["NONE"],RUNTIME_FINGERPRINTS:["NODE@22.13.0"],PACKAGE_MANAGER_FINGERPRINTS:["NPM@10.9.2"],REGISTRIES:["https://registry.npmjs.org"],AVAILABLE_DISK_MIB:4096,AVAILABLE_MEMORY_MIB:2048,OBSERVED_AT:new Date(T).toISOString(),VALID_UNTIL:new Date(T+60000).toISOString(),...overrides})}
function backend(){return{BACKEND_ID:"provider-a",ROUTER_PRIORITY:1,EXECUTION_CLASS_REALIZATION:"HOSTED",CAPABILITIES:["NETWORK_EGRESS","PROCESS_EXEC","SOURCE_READ"],VERIFIER_POLICY_SHA256S:[V],READY:true,EXECUTION_TRANSPORT_READY:true}}
async function registry(p=profile()){const dir=await mkdtemp(join(tmpdir(),"p5-")),path=join(dir,"registry.json");await initializeProviderCapabilityRegistryV1(path,{REGISTRY_ID:"reg"},T);await upsertProviderCapabilityProfileV1(path,p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"up",RUNTIME_NOW_MS:T+1});return{dir,path,state:await readProviderCapabilityRegistryV1(path)}}
function required(){return resolveRequiredCapabilitiesV1(compileExecutionEnvironmentContractV1(task(),{LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.13.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",REGISTRIES:["https://registry.npmjs.org"],MIN_DISK_MIB:1024,MIN_MEMORY_MIB:1024,REQUIRED_PROVIDER_CAPABILITIES:["REGISTRY_NPM"]}))}
test("P5 resolver preserves frozen task capabilities and adds runtime-owned overlay",()=>{const r=required();assert.deepEqual(r.TASK_CAPABILITIES,["NETWORK_EGRESS","PROCESS_EXEC","SOURCE_READ"]);assert.deepEqual(r.REQUIRED_CAPABILITIES,["NETWORK_EGRESS","PROCESS_EXEC","REGISTRY_NPM","SOURCE_READ"]);assert.equal(r.RUNTIME_VERSION,"22.13.0")});
test("P5 environment contract is content-bound and tamper fails",()=>{const c=compileExecutionEnvironmentContractV1(task());assert.throws(()=>resolveRequiredCapabilitiesV1({...c,OS_CLASS:"WINDOWS"}),/SHA256_MISMATCH/)});
test("P5 provider registry persists profile and semantic idempotent replay",async()=>{const f=await registry();try{const replay=await upsertProviderCapabilityProfileV1(f.path,profile(),{EXPECTED_STATE_VERSION:999,IDEMPOTENCY_KEY:"up",RUNTIME_NOW_MS:T+9});assert.equal(replay.replay,true)}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 stale provider profile is rejected before admission",async()=>{const f=await registry();try{assert.equal(resolveCurrentProviderCapabilityProfileV1(f.state,"provider-a",T+60000).code,"PROVIDER_PROFILE_STALE")}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 complete capability environment policy and readiness match admits",async()=>{const f=await registry();try{const e=evaluateCapabilityAdmissionV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:backend(),executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,allowedCostClasses:["FREE"]});assert.equal(e.decision,"ADMIT");assert.deepEqual(e.reasons,[])}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 runtime version mismatch is capability mismatch not application failure",async()=>{const f=await registry(profile({RUNTIME_FINGERPRINTS:["NODE@20.0.0"]}));try{const e=evaluateCapabilityAdmissionV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:backend(),executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V});assert.equal(e.decision,"REJECT");assert.ok(e.reasons.includes("RUNTIME_VERSION_UNSATISFIED"))}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 registry and capacity mismatch fail closed",async()=>{const f=await registry(profile({REGISTRIES:[],AVAILABLE_MEMORY_MIB:512}));try{const e=evaluateCapabilityAdmissionV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:backend(),executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V});assert.ok(e.reasons.includes("REGISTRY_UNAVAILABLE"));assert.ok(e.reasons.includes("MEMORY_CAPACITY_UNSATISFIED"))}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 adapter readiness health and cost are independent admission gates",async()=>{const f=await registry(profile({EXECUTION_ADAPTER_STATE:"BOOTSTRAP_REQUIRED",HEALTH_STATE:"DEGRADED",COST_CLASS:"PAID"}));try{const e=evaluateCapabilityAdmissionV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:backend(),executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,allowedCostClasses:["FREE"]});for(const x of ["EXECUTION_ADAPTER_NOT_READY","PROVIDER_HEALTH_UNSATISFIED","COST_POLICY_MISMATCH"])assert.ok(e.reasons.includes(x))}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 composes existing P3 frozen task capability gate",async()=>{const f=await registry();try{const b=backend();b.CAPABILITIES=b.CAPABILITIES.filter(x=>x!=="SOURCE_READ");const e=evaluateCapabilityAdmissionV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:b,executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V});assert.ok(e.reasons.includes("P3:CAPABILITY_MISMATCH"))}finally{await rm(f.dir,{recursive:true,force:true})}});
test("P5 admission receipt binds required set and observed profile identity",async()=>{const f=await registry();try{const r=buildCapabilityAdmissionReceiptV1({requiredCapabilities:required(),registry:f.state,providerId:"provider-a",runtimeNowMs:T+2,backendCandidate:backend(),executionClass:"HOSTED_ELIGIBLE",verifierPolicySha256:V,allowedCostClasses:["FREE"]});assert.equal(r.DECISION,"ADMIT");assert.match(r.RECEIPT_SHA256,/^[0-9a-f]{64}$/);assert.equal(r.OBSERVED_PROFILE_SHA256,f.state.PROFILES["provider-a"].PROFILE_SHA256)}finally{await rm(f.dir,{recursive:true,force:true})}});
