import test from "node:test";
import assert from "node:assert/strict";
import {compileVerificationScopeV1,buildAcceptanceDependencyGraphV1,evaluateAcceptanceNodeV1,planLeastPrivilegeEvidenceStagingV1,evaluateAuthorityExpansionV1,consumeRuntimeEvidenceInvalidationV1,evaluateContentIdentityReuseAcceptanceV1,evaluateDependencySecurityPolicyV1,compileAcceptancePolicyManifestV1} from "../pilote/rev51/acceptance-policy-v1.mjs";

test("P28 verification scope keeps CI distinct from live/project/release",()=>{const s=compileVerificationScopeV1({source:"PASS",ci:"PASS",liveAttestation:"BLOCKED",projectAcceptance:"PENDING",releaseAcceptance:"NOT_GRANTED"});assert.equal(s.ci,"PASS");assert.equal(s.liveAttestation,"BLOCKED");assert.equal(s.releaseAcceptance,"NOT_GRANTED")});
test("P28 acceptance DAG denies child with unsatisfied parent",()=>{const g=buildAcceptanceDependencyGraphV1([{nodeId:"CI",status:"PENDING",acceptancePolicyVersion:"1"},{nodeId:"LIVE",prerequisites:["CI"],requiredEvidenceTypes:["LIVE_RECEIPT"],acceptancePolicyVersion:"1"}]);const r=evaluateAcceptanceNodeV1({graph:g,nodeId:"LIVE",evidenceTypes:["LIVE_RECEIPT"]});assert.equal(r.reason,"UNSATISFIED_REQUIRED_PARENT")});
test("P28 acceptance DAG requires declared evidence",()=>{const g=buildAcceptanceDependencyGraphV1([{nodeId:"CI",status:"PASS",acceptancePolicyVersion:"1"},{nodeId:"PROJECT",prerequisites:["CI"],requiredEvidenceTypes:["PROJECT_RECEIPT"],acceptancePolicyVersion:"1"}]);assert.equal(evaluateAcceptanceNodeV1({graph:g,nodeId:"PROJECT",evidenceTypes:[]}).reason,"REQUIRED_EVIDENCE_MISSING");assert.equal(evaluateAcceptanceNodeV1({graph:g,nodeId:"PROJECT",evidenceTypes:["PROJECT_RECEIPT"]}).decision,"ACCEPT")});
test("P28 evidence staging requests no authority above required stage",()=>{assert.deepEqual(planLeastPrivilegeEvidenceStagingV1({requiredEvidence:[{stage:"METADATA"}]}).stages,["METADATA"]);assert.deepEqual(planLeastPrivilegeEvidenceStagingV1({requiredEvidence:[{stage:"TELEMETRY"}]}).stages,["METADATA","TELEMETRY"])});
test("P28 new external auth defers during development",()=>{const r=evaluateAuthorityExpansionV1({currentAuthority:["PROVIDER_METADATA_READ"],requestedDelta:["PROVIDER_TELEMETRY_READ"],newExternalSecret:true,projectDevelopmentComplete:false});assert.equal(r.decision,"DEFERRED_POST_DEVELOPMENT_CREDENTIAL_BIND")});
test("P28 mutation cost destructive or release authority is hard boundary",()=>{for(const k of ["providerMutation","costBoundaryExpansion","destructiveAuthority","releaseAuthority"]){const r=evaluateAuthorityExpansionV1({requestedDelta:["X"],[k]:true});assert.equal(r.decision,"HARD_AUTHORITY_BOUNDARY")}});
test("P28 preapproved least-privilege read delta may continue",()=>{const r=evaluateAuthorityExpansionV1({currentAuthority:["META"],requestedDelta:["TELEMETRY"],preapprovedReadCapabilities:["TELEMETRY"]});assert.equal(r.decision,"ALLOW")});
test("P28 consumes Runtime invalidation only for affected acceptance nodes",()=>{const r=consumeRuntimeEvidenceInvalidationV1({runtimeInvalidation:{staleEvidenceIds:["e2"]},acceptanceNodes:[{nodeId:"SOURCE",requiredEvidenceIds:["e1"]},{nodeId:"LIVE",requiredEvidenceIds:["e2"]}]});assert.deepEqual(r.affectedAcceptanceNodes,["LIVE"]);assert.equal(r.fullRevalidationRequired,false)});
test("P28 exact content identity reuse accepts only Runtime-marked reusable evidence",()=>{const r=evaluateContentIdentityReuseAcceptanceV1({exactContentIdentity:true,evidence:[{EVIDENCE_ID:"e1",REUSABLE:true,REASON:"EXACT_CONTENT_IDENTITY_MATCH"},{EVIDENCE_ID:"e2",REUSABLE:false,REASON:"METADATA_REEVALUATION_REQUIRED"}]});assert.deepEqual(r.reusableEvidenceIds,["e1"])});
test("P28 dependency security policy can block defer or release without mutation authority",()=>{const o=(c,h)=>({MUTATION_AUTHORITY:false,SEVERITY_COUNTS:{CRITICAL:c,HIGH:h}});assert.equal(evaluateDependencySecurityPolicyV1({observation:o(1,0),policy:{maxCritical:0,maxHigh:1}}).decision,"BLOCK");assert.equal(evaluateDependencySecurityPolicyV1({observation:o(0,2),policy:{maxCritical:0,maxHigh:1}}).decision,"DEFER");assert.equal(evaluateDependencySecurityPolicyV1({observation:o(0,1),policy:{maxCritical:0,maxHigh:1}}).decision,"RELEASE")});
test("P28 acceptance policy manifest denies unscoped remote verified semantics",()=>{const s=compileVerificationScopeV1({}),g=buildAcceptanceDependencyGraphV1([{nodeId:"SOURCE",acceptancePolicyVersion:"1"}]);const m=compileAcceptancePolicyManifestV1({verificationScopeSha256:s.VERIFICATION_SCOPE_SHA256,acceptanceGraphSha256:g.ACCEPTANCE_GRAPH_SHA256});assert.equal(m.REMOTE_VERIFIED_WITHOUT_SCOPE,"DENY");assert.equal(m.PROJECT_ACCEPTED_NOT_RELEASE_AUTHORITY,true)});
