import test from "node:test";
import assert from "node:assert/strict";
import {
  A5_AUTHORITATIVE_BINDING,
  computePiloteA5IntentSha256V1,
  createA5CrossStackBindingReceiptV1,
  validateA5CrossStackBindingV1,
  validatePiloteA5IntentV1,
  validateRuntimeA5EnforcementBoundaryV1
} from "../runtime/rev51/pilote-capability-resource-security-consumer-v1.mjs";

const CONTRACT_SET="a8b220c92a47306061e9aca1c65077d357b00bda12e9daad4f37215256083f4a";
const TASK_HASH="d2fb156b45cb2f78f97e1550b2c972ada5e739ae0477fdc2944cb8e5b23ddb66";
const EXEC_HASH="68f231d23a0181ee08bab90df8619ae8b4e8c8ba9ba57ccbe1fa02d75069127e";

function baseA5(overrides={}) {
  return {
    INTENT_TYPE:"PILOTE_CAPABILITY_RESOURCE_SECURITY_INTENT_V1", INTENT_VERSION:"1.0.0",
    CANONICALIZATION_ID:"ATELIER_EXECUTION_CANONICAL_JSON_V1", PROJECT_ID:"ATELIER-PILOTE", PHASE_ID:"R42-P2P3", TASK_ID:"R42-FIXTURE-READ-001",
    TASK_CONTRACT_SHA256:TASK_HASH, EXECUTION_INTENT_SHA256:EXEC_HASH, CAPABILITY_REQUIREMENT_REFS:["SOURCE_READ"],
    RESOURCE_INTENT:{CPU_MIN_MILLICORES:null,MEMORY_MIN_MIB:null,DISK_MIN_MIB:null,GPU_COUNT:null,GPU_MEMORY_MIN_MIB:null,GPU_CAPABILITY_CLASS:null},
    SECURITY_REQUIREMENT:{ISOLATION_CLASS:"DEFAULT",NETWORK_CLASS:"INHERIT_TASK",DATA_ACCESS_CLASS:"INHERIT_TASK",SECRET_CLASS:"INHERIT_TASK"},
    CAPABILITY_ATTESTATION_POLICY:"STATIC_AND_DYNAMIC_REQUIRED", CAPABILITY_DRIFT_POLICY:"FAIL_CLOSED",
    RESOURCE_OWNERSHIP_PROOF_POLICY:"DURABLE_PROOF_REQUIRED_BEFORE_DESTRUCTIVE_ACTION", HOST_MOUNT_POLICY:"DENY_DEFAULT",
    HOST_SECRET_INHERITANCE:"DENY", PRIVILEGED_WORKER:"DENY_DEFAULT", UNTRUSTED_CODE_ON_PERSISTENT_WORKER:"DENY",
    JOB_SCOPED_CREDENTIAL_LEASE:"REQUIRED", BOOTSTRAP_CREDENTIAL_PRIVILEGED_JOB_EQUIVALENCE:"DENY",
    UNATTESTED_WORKER_PRIVILEGED_JOB_CREDENTIAL:"DENY", WARM_REUSE_SANITATION_RECEIPT:"REQUIRED",
    STRUCTURED_ENTRYPOINT:"REQUIRED", SHELL_EXECUTION:"DENY_DEFAULT", SECRET_PERSISTENCE:"DENY",
    CONTRACT_SET_REF:{ID:"ATELIER_REV51_CONTRACT_SET_V1",VERSION:"1.0.0",SHA256:CONTRACT_SET},
    A5_INTENT_SHA256:"846f062498e3b12262d2d4b1c78b4bffa6e17c80db5e1f40f335fc5e6f606027",
    ...overrides
  };
}

const vectors=[
  ["V001_VALID_MINIMAL",baseA5(),true,[]],
  ["V002_RUNTIME_PROVIDER_ID_DENY",baseA5({PROVIDER_ID:"DIGITALOCEAN",A5_INTENT_SHA256:"0".repeat(64)}),false,["A5_TOP_LEVEL_FIELDS_MISMATCH","FORBIDDEN_RUNTIME_OWNED_KEY:$.PROVIDER_ID","A5_INTENT_SHA256_MISMATCH"]],
  ["V003_ATTESTATION_ID_DENY",baseA5({ATTESTATION_ID:"att-1",A5_INTENT_SHA256:"0".repeat(64)}),false,["A5_TOP_LEVEL_FIELDS_MISMATCH","FORBIDDEN_RUNTIME_OWNED_KEY:$.ATTESTATION_ID","A5_INTENT_SHA256_MISMATCH"]],
  ["V004_CAPABILITY_ATTESTATION_WEAKEN_DENY",baseA5({CAPABILITY_ATTESTATION_POLICY:"STATIC_ONLY",A5_INTENT_SHA256:"0".repeat(64)}),false,["CAPABILITY_ATTESTATION_POLICY_MISMATCH","A5_INTENT_SHA256_MISMATCH"]],
  ["V005_PRIVILEGED_WORKER_ALLOW_DENY",baseA5({PRIVILEGED_WORKER:"ALLOW",A5_INTENT_SHA256:"0".repeat(64)}),false,["PRIVILEGED_WORKER_MISMATCH","A5_INTENT_SHA256_MISMATCH"]],
  ["V006_BOOTSTRAP_PRIV_EQUIVALENCE_DENY",baseA5({BOOTSTRAP_CREDENTIAL_PRIVILEGED_JOB_EQUIVALENCE:"ALLOW",A5_INTENT_SHA256:"0".repeat(64)}),false,["BOOTSTRAP_CREDENTIAL_PRIVILEGED_JOB_EQUIVALENCE_MISMATCH","A5_INTENT_SHA256_MISMATCH"]],
  ["V007_SECRET_PERSISTENCE_DENY",baseA5({SECRET_PERSISTENCE:"ALLOW",A5_INTENT_SHA256:"0".repeat(64)}),false,["SECRET_PERSISTENCE_MISMATCH","A5_INTENT_SHA256_MISMATCH"]],
  ["V008_CONTRACT_SET_DRIFT_DENY",baseA5({CONTRACT_SET_REF:{ID:"ATELIER_REV51_CONTRACT_SET_V1",VERSION:"1.0.0",SHA256:"0".repeat(64)},A5_INTENT_SHA256:"fbd14b2296e00896e11a2afab00db50c086eec0182efa18e87b669d99902e7a6"}),false,["CONTRACT_SET_REF_MISMATCH"]]
];

function task(overrides={}) { return {PROJECT_ID:"ATELIER-PILOTE",PHASE_ID:"R42-P2P3",TASK_ID:"R42-FIXTURE-READ-001",TASK_CONTRACT_HASH:TASK_HASH,CAPABILITY_REQUIREMENTS:["SOURCE_READ"],...overrides}; }
function intent(overrides={}) { return {PROJECT_ID:"ATELIER-PILOTE",PHASE_ID:"R42-P2P3",TASK_ID:"R42-FIXTURE-READ-001",TASK_CONTRACT_SHA256:TASK_HASH,INTENT_SHA256:EXEC_HASH,CAPABILITY_REQUIREMENTS:["SOURCE_READ"],RESOURCE_INTENT:baseA5().RESOURCE_INTENT,SECURITY_REQUIREMENT:baseA5().SECURITY_REQUIREMENT,...overrides}; }
function plan(overrides={}) { return {EXECUTION_INTENT_SHA256:EXEC_HASH,CONTRACT_SET_SHA256:CONTRACT_SET,RESOURCE_INTENT:baseA5().RESOURCE_INTENT,SECURITY_REQUIREMENT:baseA5().SECURITY_REQUIREMENT,...overrides}; }
function observed(overrides={}) { return {STATIC_CAPABILITY_ATTESTATION_VALID:true,DYNAMIC_CAPABILITY_ATTESTATION_VALID:true,CAPABILITY_DRIFT_DETECTED:false,DESTRUCTIVE_ACTION:false,RESOURCE_OWNERSHIP_PROOF_DURABLE:false,BOOTSTRAP_CREDENTIAL_CLASS:"BOOTSTRAP_ONLY",JOB_CREDENTIAL_LEASE_SCOPE:"JOB_SCOPED",WORKER_ATTESTED:true,PRIVILEGED_JOB_CREDENTIAL_PRESENT:false,WORKER_PRIVILEGED:false,HOST_MOUNT_GRANTED:false,HOST_SECRET_INHERITED:false,UNTRUSTED_CODE_ON_PERSISTENT_WORKER:false,WARM_REUSE:false,SANITATION_RECEIPT_VALID:false,STRUCTURED_ENTRYPOINT_USED:true,SHELL_EXECUTION_USED:false,SECRET_PERSISTED:false,...overrides}; }

test("A5 authoritative identities are exact",()=>{
  assert.equal(A5_AUTHORITATIVE_BINDING.HEAD,"47607a346f57077b46f3df527fae5a51e960243b");
  assert.equal(A5_AUTHORITATIVE_BINDING.TREE,"22871e691daedc9a922de95f6d7820b93c136e81");
  assert.equal(A5_AUTHORITATIVE_BINDING.MODULE_SHA256,"a38d88c13f497007a6903297713d064f5f71188aa5a734423f3a7d0838fed1eb");
  assert.equal(A5_AUTHORITATIVE_BINDING.SCHEMA_SHA256,"1bbcd5a6acf38f677527ad69117c210b0c114754ba96c36edc268f7cffd948f8");
});
for (const [id,input,ok,errors] of vectors) test(`${id} reproduces A5 expected result`,()=>{ const actual=validatePiloteA5IntentV1(input); assert.equal(actual.ok,ok); assert.deepEqual(actual.errors,errors); });
test("canonical A5 hash matches authoritative V001",()=>assert.equal(computePiloteA5IntentSha256V1(baseA5()),"846f062498e3b12262d2d4b1c78b4bffa6e17c80db5e1f40f335fc5e6f606027"));
test("Task Contract, A2 execution intent, Runtime plan and A5 bind exactly",()=>assert.deepEqual(validateA5CrossStackBindingV1(task(),intent(),plan(),baseA5()),{ok:true,errors:[]}));
test("capability requirement drift is rejected",()=>assert.ok(validateA5CrossStackBindingV1(task(),intent({CAPABILITY_REQUIREMENTS:["SOURCE_READ","NETWORK_EGRESS"]}),plan(),baseA5()).errors.includes("CAPABILITY_REQUIREMENT_BINDING_MISMATCH")));
test("resource intent drift is rejected",()=>assert.ok(validateA5CrossStackBindingV1(task(),intent(),plan({RESOURCE_INTENT:{...baseA5().RESOURCE_INTENT,CPU_MIN_MILLICORES:1000}}),baseA5()).errors.includes("RESOURCE_INTENT_BINDING_MISMATCH")));
test("security requirement drift is rejected",()=>assert.ok(validateA5CrossStackBindingV1(task(),intent(),plan({SECURITY_REQUIREMENT:{...baseA5().SECURITY_REQUIREMENT,ISOLATION_CLASS:"ISOLATED"}}),baseA5()).errors.includes("SECURITY_REQUIREMENT_BINDING_MISMATCH")));
test("runtime A5 enforcement positive path passes",()=>assert.deepEqual(validateRuntimeA5EnforcementBoundaryV1(observed()),{ok:true,errors:[]}));
test("capability drift fails closed",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({CAPABILITY_DRIFT_DETECTED:true})).errors.includes("CAPABILITY_DRIFT_FAIL_CLOSED")));
test("destructive action requires durable ownership proof",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({DESTRUCTIVE_ACTION:true})).errors.includes("DURABLE_RESOURCE_OWNERSHIP_PROOF_REQUIRED")));
test("credential class separation is enforced",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({BOOTSTRAP_CREDENTIAL_CLASS:"PRIVILEGED_JOB"})).errors.includes("BOOTSTRAP_CREDENTIAL_PRIVILEGED_JOB_EQUIVALENCE_DENIED")));
test("worker privilege boundary is enforced",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({WORKER_PRIVILEGED:true})).errors.includes("PRIVILEGED_WORKER_DENY_DEFAULT")));
test("secret persistence boundary is enforced",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({SECRET_PERSISTED:true})).errors.includes("SECRET_PERSISTENCE_DENIED")));
test("warm reuse requires sanitation receipt",()=>assert.ok(validateRuntimeA5EnforcementBoundaryV1(observed({WARM_REUSE:true})).errors.includes("WARM_REUSE_SANITATION_RECEIPT_REQUIRED")));
test("binding receipt reports every requested A5 boundary PASS",()=>{
  const r=createA5CrossStackBindingReceiptV1(task(),intent(),plan(),baseA5(),observed());
  for(const key of ["CAPABILITY_REQUIREMENT_BINDING","RESOURCE_INTENT_BINDING","SECURITY_REQUIREMENT_BINDING","CAPABILITY_ATTESTATION_BOUNDARY","CAPABILITY_DRIFT_BOUNDARY","RESOURCE_OWNERSHIP_PROOF_BOUNDARY","CREDENTIAL_CLASS_SEPARATION","WORKER_PRIVILEGE_BOUNDARY","SECRET_PERSISTENCE_BOUNDARY"]) assert.equal(r[key],"PASS");
});
