import test from "node:test";import assert from "node:assert/strict";import{mkdtemp,rm,readFile,writeFile}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{initializeWorkerSanitationReceiptV1,readWorkerSanitationReceiptV1,validateWarmReuseGateV1,consumeWorkerSanitationReceiptV1,reconcileWorkerSanitationReceiptExpiryV1,invalidateWorkerSanitationReceiptV1}from"../runtime/rev51/durable-worker-sanitation-receipt-v1.mjs";
const P="a".repeat(64),N="b".repeat(64),A="c".repeat(64),S="d".repeat(64),C="e".repeat(64),T0=Date.parse("2026-09-24T00:00:00Z"),T1=T0+60000;
function init(x={}){return{RECEIPT_ID:"san-1",WORKER_ID:"worker-1",PREVIOUS_WORKER_JOB_SHA256:P,NEXT_WORKER_JOB_SHA256:N,NEXT_WORKER_READY_ATTESTATION_HASH:A,SANITATION_PROFILE_SHA256:S,CREDENTIAL_REVOCATION_PROOF_SHA256:C,PREVIOUS_JOB_TERMINAL:true,CREDENTIAL_LEASE_REVOKED:true,WORKDIR_RESET:true,PROCESS_NAMESPACE_CLEAN:true,NETWORK_NAMESPACE_RESET:true,HOST_MOUNT_ABSENT:true,SECRET_SCAN_CLEAN:true,UNTRUSTED_CODE_ON_PERSISTENT_WORKER:false,EXPIRES_AT_MS:T1,...x}}
async function fx(){const d=await mkdtemp(join(tmpdir(),"p2l-"));return{d,p:join(d,"receipt.json")}}async function w(fn){const f=await fx();try{await fn(f)}finally{await rm(f.d,{recursive:true,force:true})}}
const gate=(x={})=>({WARM_REUSE:true,WORKER_ID:"worker-1",NEXT_WORKER_JOB_SHA256:N,NEXT_WORKER_READY_ATTESTATION_HASH:A,UNTRUSTED_CODE_ON_PERSISTENT_WORKER:false,...x});
test("init available sanitation receipt",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(s.RECEIPT_STATUS,"AVAILABLE")}));
test("missing sanitation fact denied",()=>w(async f=>{await assert.rejects(()=>initializeWorkerSanitationReceiptV1(f.p,init({SECRET_SCAN_CLEAN:false}),T0),/SANITATION_FACT_REQUIRED/)}));
test("untrusted persistent code denied",()=>w(async f=>{await assert.rejects(()=>initializeWorkerSanitationReceiptV1(f.p,init({UNTRUSTED_CODE_ON_PERSISTENT_WORKER:true}),T0),/UNTRUSTED_CODE/)}));
test("non warm reuse does not require receipt",()=>{assert.deepEqual(validateWarmReuseGateV1(null,{WARM_REUSE:false},T0),{ok:true,code:"WARM_REUSE_NOT_REQUESTED"})});
test("exact warm reuse binding passes",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(validateWarmReuseGateV1(s,gate(),T0+1).ok,true)}));
test("wrong worker denied",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(validateWarmReuseGateV1(s,gate({WORKER_ID:"worker-2"}),T0+1).code,"SANITATION_WORKER_BINDING_MISMATCH")}));
test("wrong next job denied",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(validateWarmReuseGateV1(s,gate({NEXT_WORKER_JOB_SHA256:P}),T0+1).code,"SANITATION_NEXT_JOB_BINDING_MISMATCH")}));
test("wrong next attestation denied",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(validateWarmReuseGateV1(s,gate({NEXT_WORKER_READY_ATTESTATION_HASH:P}),T0+1).code,"SANITATION_ATTESTATION_BINDING_MISMATCH")}));
test("consume exactly once",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);const q={EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"consume-1",RUNTIME_NOW_MS:T0+1,WORKER_ID:"worker-1",NEXT_WORKER_JOB_SHA256:N,NEXT_WORKER_READY_ATTESTATION_HASH:A};const a=await consumeWorkerSanitationReceiptV1(f.p,q),b=await consumeWorkerSanitationReceiptV1(f.p,{...q,RUNTIME_NOW_MS:T0+9});assert.equal(a.state.RECEIPT_STATUS,"CONSUMED");assert.equal(b.replay,true)}));
test("consumed receipt cannot authorize another use",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);await consumeWorkerSanitationReceiptV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"consume-1",RUNTIME_NOW_MS:T0+1,WORKER_ID:"worker-1",NEXT_WORKER_JOB_SHA256:N,NEXT_WORKER_READY_ATTESTATION_HASH:A});const s=await readWorkerSanitationReceiptV1(f.p);assert.equal(validateWarmReuseGateV1(s,gate(),T0+2).code,"SANITATION_RECEIPT_NOT_AVAILABLE")}));
test("expired receipt denied",()=>w(async f=>{const s=await initializeWorkerSanitationReceiptV1(f.p,init(),T0);assert.equal(validateWarmReuseGateV1(s,gate(),T1).code,"SANITATION_RECEIPT_EXPIRED")}));
test("expiry reconciliation durable",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);const r=await reconcileWorkerSanitationReceiptExpiryV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"exp-1",RUNTIME_NOW_MS:T1});assert.equal(r.state.RECEIPT_STATUS,"EXPIRED");assert.equal((await readWorkerSanitationReceiptV1(f.p)).RECEIPT_STATUS,"EXPIRED")}));
test("policy invalidation durable",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);const r=await invalidateWorkerSanitationReceiptV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"inv-1",RUNTIME_NOW_MS:T0+1,REASON:"POLICY_DRIFT"});assert.equal(r.state.RECEIPT_STATUS,"INVALID")}));
test("idempotency conflict denied",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);await invalidateWorkerSanitationReceiptV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"inv-1",RUNTIME_NOW_MS:T0+1,REASON:"POLICY_DRIFT"});await assert.rejects(()=>invalidateWorkerSanitationReceiptV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"inv-1",RUNTIME_NOW_MS:T0+2,REASON:"TRUST_RESET"}),/IDEMPOTENCY_KEY_CONFLICT/)}));
test("crash reopen preserves consumed state",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);await consumeWorkerSanitationReceiptV1(f.p,{EXPECTED_STATE_VERSION:0,IDEMPOTENCY_KEY:"consume-1",RUNTIME_NOW_MS:T0+1,WORKER_ID:"worker-1",NEXT_WORKER_JOB_SHA256:N,NEXT_WORKER_READY_ATTESTATION_HASH:A});assert.equal((await readWorkerSanitationReceiptV1(f.p)).RECEIPT_STATUS,"CONSUMED")}));
test("event ledger tamper rejected",()=>w(async f=>{await initializeWorkerSanitationReceiptV1(f.p,init(),T0);const x=JSON.parse(await readFile(f.p,"utf8"));x.EVENT_LEDGER[0].EVENT_SHA256="0".repeat(64);await writeFile(f.p,JSON.stringify(x));await assert.rejects(()=>readWorkerSanitationReceiptV1(f.p),/SANITATION_EVENT_HASH_MISMATCH/)}));
