import test from"node:test";import assert from"node:assert/strict";import{mkdtemp,rm,readFile,writeFile}from"node:fs/promises";import{join}from"node:path";import{tmpdir}from"node:os";import{initializeCancellationReconciliationV1,readCancellationReconciliationV1,recordCancellationOperationV1,deriveCancellationReconciliationProjectionV1}from"../runtime/rev51/durable-cancellation-reconciliation-v1.mjs";
const PLAN="a".repeat(64),OBS="b".repeat(64),T=Date.parse("2026-09-24T00:00:00Z");async function fx(){const d=await mkdtemp(join(tmpdir(),"p2i-"));return{d,p:join(d,"c.json")}};async function init(f){return initializeCancellationReconciliationV1(f.p,{EXECUTION_PLAN_SHA256:PLAN,CANCELLATION_FENCE_TOKEN:"f1"},T)}
const unknown={OPERATION_ID:"op1",RESERVATION_ID:"r1",RESULT:"OUTCOME_UNKNOWN",OBSERVATION_SHA256:OBS,IDEMPOTENCY_KEY:"k1",SUBMITTED_FENCE_TOKEN:"f1",EXPECTED_STATE_VERSION:0,RUNTIME_NOW_MS:T+1};
test("initialize/reopen",async()=>{const f=await fx();try{await init(f);assert.equal((await readCancellationReconciliationV1(f.p)).STATE_VERSION,0)}finally{await rm(f.d,{recursive:true,force:true})}});
test("unknown recorded and blocks terminal projection",async()=>{const f=await fx();try{await init(f);const r=await recordCancellationOperationV1(f.p,unknown);assert.equal(deriveCancellationReconciliationProjectionV1(r.state).OUTCOME_UNKNOWN,1)}finally{await rm(f.d,{recursive:true,force:true})}});
test("same operation reconcile terminal",async()=>{const f=await fx();try{await init(f);await recordCancellationOperationV1(f.p,unknown);const r=await recordCancellationOperationV1(f.p,{...unknown,RESULT:"SUCCEEDED",IDEMPOTENCY_KEY:"k2",EXPECTED_STATE_VERSION:1,RUNTIME_NOW_MS:T+2});assert.equal(deriveCancellationReconciliationProjectionV1(r.state).ALL_TERMINAL,true)}finally{await rm(f.d,{recursive:true,force:true})}});
test("blind retry denied",async()=>{const f=await fx();try{await init(f);await recordCancellationOperationV1(f.p,unknown);await assert.rejects(recordCancellationOperationV1(f.p,{...unknown,IDEMPOTENCY_KEY:"k2",EXPECTED_STATE_VERSION:1,RUNTIME_NOW_MS:T+2}),/BLIND_RETRY_DENIED/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("terminal without unknown denied",async()=>{const f=await fx();try{await init(f);await assert.rejects(recordCancellationOperationV1(f.p,{...unknown,RESULT:"FAILED"}),/UNKNOWN_OPERATION_REQUIRES_INITIAL_OUTCOME_UNKNOWN/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("stale fence denied",async()=>{const f=await fx();try{await init(f);await assert.rejects(recordCancellationOperationV1(f.p,{...unknown,SUBMITTED_FENCE_TOKEN:"old"}),/CANCELLATION_FENCE_MISMATCH/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("cas denied",async()=>{const f=await fx();try{await init(f);await assert.rejects(recordCancellationOperationV1(f.p,{...unknown,EXPECTED_STATE_VERSION:9}),/RECONCILIATION_STATE_CAS_MISMATCH/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("exact replay pass",async()=>{const f=await fx();try{await init(f);await recordCancellationOperationV1(f.p,unknown);const r=await recordCancellationOperationV1(f.p,{...unknown,RUNTIME_NOW_MS:T+99});assert.equal(r.replay,true)}finally{await rm(f.d,{recursive:true,force:true})}});
test("changed replay denied",async()=>{const f=await fx();try{await init(f);await recordCancellationOperationV1(f.p,unknown);await assert.rejects(recordCancellationOperationV1(f.p,{...unknown,OBSERVATION_SHA256:"c".repeat(64),RUNTIME_NOW_MS:T+2}),/RECONCILIATION_IDEMPOTENCY_CONFLICT/)}finally{await rm(f.d,{recursive:true,force:true})}});
test("tamper denied",async()=>{const f=await fx();try{await init(f);const x=JSON.parse(await readFile(f.p,"utf8"));x.EVENT_LEDGER[0].EVENT_SHA256="0".repeat(64);await writeFile(f.p,JSON.stringify(x));await assert.rejects(readCancellationReconciliationV1(f.p),/EVENT_HASH_MISMATCH/)}finally{await rm(f.d,{recursive:true,force:true})}});
