import test from "node:test";
import assert from "node:assert/strict";
import {buildExactRuntimeProvisionSpecV1,evaluateProvisionedEnvironmentV1,buildExactRuntimeProvisionReceiptV1,validateExecutionStartProvisioningV1} from "../runtime/rev51/exact-runtime-provisioning-v1.mjs";
const H=x=>x.repeat(64), IMG=`sha256:${H("4")}`;
function req(){return{SCHEMA_ID:"CAPABILITY_REQUIREMENT_SET_V1",REQUIRED_CAPABILITIES_SHA256:H("1"),EXECUTION_ENVIRONMENT_CONTRACT_SHA256:H("2"),LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.13.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",OS_CLASS:"LINUX",ARCH_CLASS:"X64",LIBC_CLASS:"GLIBC",CONTAINER_IMAGE_DIGEST:IMG,REGISTRIES:["https://registry.npmjs.org"],MIN_DISK_MIB:1024,MIN_MEMORY_MIB:512}}
function prof(){return{PROVIDER_ID:"provider-a",PROFILE_SHA256:H("3")}}
function adm(){return{SCHEMA_ID:"CAPABILITY_ADMISSION_RECEIPT_V1",DECISION:"ADMIT",REQUIRED_CAPABILITIES_SHA256:H("1"),PROVIDER_ID:"provider-a",OBSERVED_PROFILE_SHA256:H("3"),RECEIPT_SHA256:H("5")}}
function spec(){return buildExactRuntimeProvisionSpecV1({requiredCapabilities:req(),admissionReceipt:adm(),providerProfile:prof()})}
function obs(over={}){return{LANGUAGE_RUNTIME:"NODE",RUNTIME_VERSION:"22.13.0",PACKAGE_MANAGER:"NPM",PACKAGE_MANAGER_VERSION:"10.9.2",OS_CLASS:"LINUX",ARCH_CLASS:"X64",LIBC_CLASS:"GLIBC",CONTAINER_IMAGE_DIGEST:IMG,AVAILABLE_DISK_MIB:2048,AVAILABLE_MEMORY_MIB:1024,PROVIDER_MUTATION_COUNT:0,CREDENTIAL_BIND_COUNT:0,...over}}
test("P6 spec binds P5 requirement admission and provider profile",()=>{const s=spec();assert.equal(s.REQUIRED_CAPABILITIES_SHA256,H("1"));assert.equal(s.PROVIDER_PROFILE_SHA256,H("3"));assert.match(s.SPEC_SHA256,/^[0-9a-f]{64}$/)});
test("P6 rejects admission requirement drift",()=>{const a=adm();a.REQUIRED_CAPABILITIES_SHA256=H("9");assert.throws(()=>buildExactRuntimeProvisionSpecV1({requiredCapabilities:req(),admissionReceipt:a,providerProfile:prof()}),/ADMISSION_REQUIREMENT_BINDING_MISMATCH/)});
test("P6 exact runtime mismatch rejects before application execution",()=>{const e=evaluateProvisionedEnvironmentV1({spec:spec(),observation:obs({RUNTIME_VERSION:"22.16.0"})});assert.equal(e.ok,false);assert.ok(e.reasons.includes("RUNTIME_VERSION_UNSATISFIED"))});
test("P6 exact package manager mismatch rejects",()=>assert.ok(evaluateProvisionedEnvironmentV1({spec:spec(),observation:obs({PACKAGE_MANAGER_VERSION:"11.0.0"})}).reasons.includes("PACKAGE_MANAGER_VERSION_UNSATISFIED")));
test("P6 platform libc and image identity are exact",()=>{const e=evaluateProvisionedEnvironmentV1({spec:spec(),observation:obs({ARCH_CLASS:"ARM64",LIBC_CLASS:"MUSL",CONTAINER_IMAGE_DIGEST:`sha256:${H("8")}`})});for(const r of["ARCH_CLASS_UNSATISFIED","LIBC_CLASS_UNSATISFIED","CONTAINER_IMAGE_DIGEST_UNSATISFIED"])assert.ok(e.reasons.includes(r))});
test("P6 capacity floor is enforced",()=>{const e=evaluateProvisionedEnvironmentV1({spec:spec(),observation:obs({AVAILABLE_DISK_MIB:512,AVAILABLE_MEMORY_MIB:256})});assert.ok(e.reasons.includes("DISK_CAPACITY_UNSATISFIED"));assert.ok(e.reasons.includes("MEMORY_CAPACITY_UNSATISFIED"))});
test("P6 slice forbids provider mutation and credential binding",()=>{const e=evaluateProvisionedEnvironmentV1({spec:spec(),observation:obs({PROVIDER_MUTATION_COUNT:1,CREDENTIAL_BIND_COUNT:1})});assert.ok(e.reasons.includes("PROVIDER_MUTATION_DENIED"));assert.ok(e.reasons.includes("CREDENTIAL_BINDING_DENIED"))});
test("P6 PASS receipt binds exact environment fingerprint",()=>{const r=buildExactRuntimeProvisionReceiptV1({spec:spec(),observation:obs()});assert.equal(r.RESULT,"PASS");assert.match(r.ENVIRONMENT_FINGERPRINT,/^[0-9a-f]{64}$/);assert.match(r.RECEIPT_SHA256,/^[0-9a-f]{64}$/)});
test("P6 execution-start reattestation detects drift",()=>{const s=spec(),r=buildExactRuntimeProvisionReceiptV1({spec:s,observation:obs()});assert.equal(validateExecutionStartProvisioningV1({spec:s,receipt:r,currentObservation:obs()}).ok,true);assert.equal(validateExecutionStartProvisioningV1({spec:s,receipt:r,currentObservation:obs({RUNTIME_VERSION:"22.16.0"})}).code,"EXECUTION_ENVIRONMENT_DRIFT")});
test("P6 spec tamper fails closed",()=>{const s=spec();assert.throws(()=>evaluateProvisionedEnvironmentV1({spec:{...s,RUNTIME_VERSION:"20.0.0"},observation:obs()}),/PROVISION_SPEC_SHA256_MISMATCH/)});
