import test from "node:test";import assert from "node:assert/strict";
import {validateP30GitHubLiveTriggerV1,compileP30GitHubLiveObservationV1} from "../pilote/rev51/p30-github-live-acceptance-v1.mjs";
const trigger={SCHEMA_ID:"R51_P30_GITHUB_LIVE_TRIGGER_V1",SCHEMA_VERSION:"1",APPROVED_SOURCE_PARENT_HEAD:"1".repeat(40),TARGET_BRANCH:"runtime-r51-p8-dependency-lock-cache",PROJECT_IDENTITY_DIGEST:"9f84671bf806417c39e804e8cc2a91940b13289767e8cfd15830ab064a159e56",PROJECT_SOURCE_MANIFEST_SHA256:"a2d8a0224cfdfb773b2f57a14e189fea79d7a0b0e447d74ac26ac70c45329697",AUTHORITATIVE_MASTER_PLAN_ID:"runtime-v016",AUTHORITATIVE_MASTER_PLAN_SHA256:"db21c3488bc6032ec96c9c8c40f82d56ed5808f25325f59c1c0cd33682d3bce2",EXECUTION_PROVIDER:"github-actions",EXECUTOR_CLASS:"repository-hosted-ci-executor",NO_NEW_PAID_RESOURCE:true,EXISTING_CI_ENVELOPE:true,CI_COST_ENVELOPE:{RUNNER_LABEL:"ubuntu-24.04",LIST_RATE_MICROUSD_PER_MINUTE:6000,TIMEOUT_MINUTES:5,MAX_LIST_PRICE_MILLI_USD:30,BILLING_ROUNDING:"CEIL_MINUTE"},ACTION_ECONOMY_FINAL_INTEGRATION_RUN:true,RELEASE_ACCEPTANCE_GRANTED:false};
test("P30 GitHub live trigger binds authoritative v016 project identity",()=>assert.match(validateP30GitHubLiveTriggerV1(trigger,{currentParentHead:"1".repeat(40),currentBranch:trigger.TARGET_BRANCH}).TRIGGER_SHA256,/^[0-9a-f]{64}$/));
test("P30 GitHub live trigger denies stale parent",()=>assert.throws(()=>validateP30GitHubLiveTriggerV1(trigger,{currentParentHead:"2".repeat(40),currentBranch:trigger.TARGET_BRANCH}),/PARENT_HEAD_MISMATCH/));
test("P30 GitHub live trigger keeps release authority separate",()=>assert.throws(()=>validateP30GitHubLiveTriggerV1({...trigger,RELEASE_ACCEPTANCE_GRANTED:true}),/RELEASE_AUTHORITY/));
test("P30 GitHub live trigger denies provider/resource envelope drift",()=>assert.throws(()=>validateP30GitHubLiveTriggerV1({...trigger,NO_NEW_PAID_RESOURCE:false}),/RESOURCE_ENVELOPE/));
test("P30 GitHub live observation passes only complete gate set",()=>{const r=compileP30GitHubLiveObservationV1({EXECUTION_HEAD:"3".repeat(40),RUN_ID:1,JOB_ID:2,SOURCE_PROVENANCE:true,BINDING_IDENTITY:true,PRODUCTION_ATTESTATION:true,PROVIDER_QUALIFICATION:true,CREDENTIAL_LIVE_BINDING:true,FAILURE_QUALIFICATION_REUSED:true,NO_NEW_PAID_RESOURCE:true,CLEANUP_SUCCESS_NOOP:true,COST_BASIS:"EXISTING_REPOSITORY_CI_ENVELOPE_NO_NEW_PROVIDER_RESOURCE",PRODUCTION_ATTESTATION_RECEIPT_SHA256:"4".repeat(64),PROVIDER_OBSERVATION_SHA256:"5".repeat(64),UNEXPECTED_BILLABLE_RESIDUE:0});assert.equal(r.PASS,true)});
test("P30 GitHub live observation fails closed on missing live gate",()=>{const r=compileP30GitHubLiveObservationV1({EXECUTION_HEAD:"3".repeat(40),RUN_ID:1,JOB_ID:2,SOURCE_PROVENANCE:true,BINDING_IDENTITY:true,PRODUCTION_ATTESTATION:true,PROVIDER_QUALIFICATION:true,CREDENTIAL_LIVE_BINDING:false,FAILURE_QUALIFICATION_REUSED:true,NO_NEW_PAID_RESOURCE:true,CLEANUP_SUCCESS_NOOP:true,COST_BASIS:"X",PRODUCTION_ATTESTATION_RECEIPT_SHA256:"4".repeat(64),PROVIDER_OBSERVATION_SHA256:"5".repeat(64)});assert.equal(r.PASS,false);assert.ok(r.MISSING.includes("CREDENTIAL_LIVE_BINDING"))});

test("P30 GitHub live trigger caps five-minute Linux list-price exposure at thirty milli-USD",()=>assert.equal(validateP30GitHubLiveTriggerV1(trigger).CI_COST_ENVELOPE.MAX_LIST_PRICE_MILLI_USD,30));
