import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { computeRev51ObjectHash } from "../runtime/rev51/contract-core.mjs";
import { initializeDurableExecutionStateV1 } from "../runtime/rev51/durable-execution-state-v1.mjs";
import { commitDurableResultAcceptanceV1 } from "../runtime/rev51/durable-result-acceptance-v1.mjs";
import { initializeArtifactReferenceIndexV1, registerAcceptedArtifactReferencesV1, sealArtifactReferenceIndexV1, releaseArtifactReferenceV1, buildZeroReferenceProofV1, readArtifactReferenceIndexV1 } from "../runtime/rev51/artifact-reference-index-v1.mjs";
import { commitPhysicalArtifactDeletionV1 } from "../runtime/rev51/artifact-physical-deletion-v1.mjs";
const T=Date.parse("2026-09-27T00:00:00Z");
const H=x=>x.repeat(64);
const sha=b=>createHash("sha256").update(b).digest("hex");
function enveloped(v){return{...v,OBJECT_SHA256:computeRev51ObjectHash({...v,OBJECT_SHA256:"0".repeat(64)})};}
async function acceptedFixture(){
  const dir=await mkdtemp(join(tmpdir(),"r51-p4-ref-"));
  const bytes=Buffer.from("accepted artifact bytes");
  const plan=enveloped({SCHEMA_ID:"RUNTIME_EXECUTION_PLAN_V1",SCHEMA_VERSION:"1",CANONICALIZATION_ID:"ATELIER_REV51_JCS_V1",UPSTREAM_OBJECT_SHA256:H("1"),OBJECT_SHA256:H("0"),EXECUTION_TRANSPORT:"DIRECT_WORKER"});
  const job=enveloped({SCHEMA_ID:"WORKER_JOB_V1",SCHEMA_VERSION:"1",CANONICALIZATION_ID:"ATELIER_REV51_JCS_V1",UPSTREAM_OBJECT_SHA256:plan.OBJECT_SHA256,OBJECT_SHA256:H("0"),EXECUTION_PLAN_HASH:plan.OBJECT_SHA256,EXECUTION_ID:"exec-1",ATTEMPT_ID:"attempt-1",FENCE_TOKEN:"fence-1"});
  const quarantined={ARTIFACT_ID:"artifact-1",CONTENT_SHA256:sha(bytes),SIZE_BYTES:bytes.length,MEDIA_TYPE:"application/octet-stream",STORAGE_CLASS:"RUNTIME_LOCAL",SECURITY_DOMAIN:"project-a",ORIGIN_EXECUTION_ID:"exec-1",CREATED_AT:"2026-09-27T00:00:00Z",RETENTION_CLASS:"UNTIL_FINAL_ACCEPTANCE",LOCATIONS:["runtime://artifact-1"],ARTIFACT_STATE:"QUARANTINED"};
  const statePath=join(dir,"state.json"), journalPath=join(dir,"acceptance.json");
  await initializeDurableExecutionStateV1(statePath,{EXECUTION_ID:"exec-1",EXECUTION_EPOCH:2,ATTEMPT_ID:"attempt-1",LEASE_GENERATION:4,FENCE_SEQUENCE:1,FENCE_TOKEN:"fence-1",DESIRED_STATE:"RUNNING",MATERIALIZED_STATE:"RESULT_QUARANTINED",PROVIDER_OPERATION_STATE:"SUCCEEDED"},T);
  const verification={VERIFICATION_RESULT:"PASS",EXECUTION_ID:"exec-1",ATTEMPT_ID:"attempt-1",FENCE_TOKEN:"fence-1",WORKER_JOB_HASH:job.OBJECT_SHA256,EXECUTION_PLAN_HASH:plan.OBJECT_SHA256,CONTENT_VERIFIED:true,FENCE_VERIFIED:true,WORKER_JOB_VERIFIED:true,EXECUTION_PLAN_VERIFIED:true,SECURITY_OUTPUT_CONTRACT_VERIFIED:true,ARTIFACT_CONTENT_BINDINGS:[{ARTIFACT_ID:quarantined.ARTIFACT_ID,CONTENT_SHA256:quarantined.CONTENT_SHA256}]};
  const committed=await commitDurableResultAcceptanceV1(statePath,journalPath,{IDEMPOTENCY_KEY:"accept",EXPECTED_STATE_VERSION:0,EXPECTED_EXECUTION_EPOCH:2,EXPECTED_LEASE_GENERATION:4,SUBMITTED_FENCE_TOKEN:"fence-1",RUNTIME_NOW_MS:T+1,PLAN:plan,WORKER_JOB:job,QUARANTINED_ARTIFACTS:[quarantined],VERIFICATION:verification});
  return{dir,bytes,plan,acceptance:committed.acceptance,artifact:committed.acceptance.ACCEPTED_ARTIFACT_MANIFEST[0]};
}
function gcStore(f,acceptanceHash=f.acceptance.ACCEPTANCE_RECORD_SHA256){return{STORE_SCHEMA_ID:"AUTHORITATIVE_GC_TOMBSTONE_V1",STORE_SCHEMA_VERSION:"1",EXECUTION_PLAN_SHA256:f.plan.OBJECT_SHA256,STATE_VERSION:1,TOMBSTONES:{[f.artifact.ARTIFACT_ID]:{ARTIFACT_ID:f.artifact.ARTIFACT_ID,ACCEPTANCE_JOURNAL_SHA256:acceptanceHash,EXECUTION_RECEIPT_SHA256:f.acceptance.EXECUTION_RECEIPT.OBJECT_SHA256,ARTIFACT_MANIFEST_SHA256:H("c"),CONTENT_SHA256:f.artifact.CONTENT_SHA256,GC_COMMITTED_AT:new Date(T+2).toISOString()}},IDEMPOTENCY_INDEX:{}};}
async function sealedReleased(f,g=gcStore(f)){
  const indexPath=join(f.dir,"reference-index.json");
  await initializeArtifactReferenceIndexV1(indexPath,{INDEX_ID:"idx-1",SECURITY_DOMAIN:"project-a"},T+2);
  await registerAcceptedArtifactReferencesV1(indexPath,f.acceptance,{IDEMPOTENCY_KEY:"register",RUNTIME_NOW_MS:T+3});
  await sealArtifactReferenceIndexV1(indexPath,[f.acceptance],{IDEMPOTENCY_KEY:"seal",RUNTIME_NOW_MS:T+4});
  let state=await readArtifactReferenceIndexV1(indexPath);const referenceId=Object.keys(state.REFERENCES)[0];
  await releaseArtifactReferenceV1(indexPath,g,{REFERENCE_ID:referenceId,IDEMPOTENCY_KEY:"release",RUNTIME_NOW_MS:T+5});
  state=await readArtifactReferenceIndexV1(indexPath);return{indexPath,state,g};
}
const retention={RUNTIME_NOW_MS:T+10,SECURITY_DOMAIN:"project-a",REFERENCED_BY_ACTIVE_EXECUTION:false,RECEIPT_RETAINED:false,CHECKPOINT_ANCESTRY_REFERENCE:false,EXPLICIT_PIN:false,ROLLBACK_ACTIVE:false,FINAL_ACCEPTANCE_TERMINAL:true};
test("complete authoritative acceptance set seals and zero-reference proof requires tombstone release",async()=>{const f=await acceptedFixture();try{const indexPath=join(f.dir,"idx.json");await initializeArtifactReferenceIndexV1(indexPath,{INDEX_ID:"idx",SECURITY_DOMAIN:"project-a"},T+2);await registerAcceptedArtifactReferencesV1(indexPath,f.acceptance,{IDEMPOTENCY_KEY:"reg",RUNTIME_NOW_MS:T+3});await sealArtifactReferenceIndexV1(indexPath,[f.acceptance],{IDEMPOTENCY_KEY:"seal",RUNTIME_NOW_MS:T+4});let state=await readArtifactReferenceIndexV1(indexPath);assert.throws(()=>buildZeroReferenceProofV1(state,f.artifact),/ACTIVE_REFERENCES/);const rid=Object.keys(state.REFERENCES)[0];await releaseArtifactReferenceV1(indexPath,gcStore(f),{REFERENCE_ID:rid,IDEMPOTENCY_KEY:"rel",RUNTIME_NOW_MS:T+5});state=await readArtifactReferenceIndexV1(indexPath);assert.equal(buildZeroReferenceProofV1(state,f.artifact).ACTIVE_REFERENCE_COUNT,0);}finally{await rm(f.dir,{recursive:true,force:true});}});
test("coverage seal fails closed if authoritative acceptance set is incomplete in index",async()=>{const f=await acceptedFixture();try{const indexPath=join(f.dir,"idx.json");await initializeArtifactReferenceIndexV1(indexPath,{INDEX_ID:"idx",SECURITY_DOMAIN:"project-a"},T+2);await assert.rejects(sealArtifactReferenceIndexV1(indexPath,[f.acceptance],{IDEMPOTENCY_KEY:"seal",RUNTIME_NOW_MS:T+4}),/COVERAGE_MISMATCH/);}finally{await rm(f.dir,{recursive:true,force:true});}});
test("reference release rejects tombstone from a different acceptance journal",async()=>{const f=await acceptedFixture();try{const indexPath=join(f.dir,"idx.json");await initializeArtifactReferenceIndexV1(indexPath,{INDEX_ID:"idx",SECURITY_DOMAIN:"project-a"},T+2);await registerAcceptedArtifactReferencesV1(indexPath,f.acceptance,{IDEMPOTENCY_KEY:"reg",RUNTIME_NOW_MS:T+3});await sealArtifactReferenceIndexV1(indexPath,[f.acceptance],{IDEMPOTENCY_KEY:"seal",RUNTIME_NOW_MS:T+4});const state=await readArtifactReferenceIndexV1(indexPath);const rid=Object.keys(state.REFERENCES)[0];await assert.rejects(releaseArtifactReferenceV1(indexPath,gcStore(f,H("f")),{REFERENCE_ID:rid,IDEMPOTENCY_KEY:"rel",RUNTIME_NOW_MS:T+5}),/TOMBSTONE_ACCEPTANCE_MISMATCH/);}finally{await rm(f.dir,{recursive:true,force:true});}});
test("physical deletion requires zero refs, retention terminality, exact tombstone, and verified bytes",async()=>{const f=await acceptedFixture();try{const{state,g}=await sealedReleased(f);const objectPath=join(f.dir,"immutable",f.artifact.SECURITY_DOMAIN,f.artifact.CONTENT_SHA256.slice(0,2),f.artifact.CONTENT_SHA256);await mkdir(dirname(objectPath),{recursive:true});await writeFile(objectPath,f.bytes);const receiptPath=join(f.dir,"delete.json");const out=await commitPhysicalArtifactDeletionV1(f.dir,receiptPath,f.artifact,state,g,retention,{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+6});assert.equal(out.result,"SUCCESS_CHANGED");await assert.rejects(readFile(objectPath),{code:"ENOENT"});assert.equal(JSON.parse(await readFile(receiptPath,"utf8")).RESULT,"SUCCESS_CHANGED");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("physical deletion replay ignores authoritative time drift",async()=>{const f=await acceptedFixture();try{const{state,g}=await sealedReleased(f);const receiptPath=join(f.dir,"delete.json");const one=await commitPhysicalArtifactDeletionV1(f.dir,receiptPath,f.artifact,state,g,retention,{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+6});const two=await commitPhysicalArtifactDeletionV1(f.dir,receiptPath,f.artifact,state,g,retention,{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+99});assert.equal(one.replay,false);assert.equal(two.replay,true);assert.equal(two.receipt.RECEIPT_SHA256,one.receipt.RECEIPT_SHA256);}finally{await rm(f.dir,{recursive:true,force:true});}});
test("already absent immutable content converges as SUCCESS_NOOP after full proof",async()=>{const f=await acceptedFixture();try{const{state,g}=await sealedReleased(f);const out=await commitPhysicalArtifactDeletionV1(f.dir,join(f.dir,"delete.json"),f.artifact,state,g,retention,{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+6});assert.equal(out.result,"SUCCESS_NOOP");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("tampered immutable bytes block physical deletion",async()=>{const f=await acceptedFixture();try{const{state,g}=await sealedReleased(f);const objectPath=join(f.dir,"immutable",f.artifact.SECURITY_DOMAIN,f.artifact.CONTENT_SHA256.slice(0,2),f.artifact.CONTENT_SHA256);await mkdir(dirname(objectPath),{recursive:true});await writeFile(objectPath,"tampered");await assert.rejects(commitPhysicalArtifactDeletionV1(f.dir,join(f.dir,"delete.json"),f.artifact,state,g,retention,{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+6}),/ARTIFACT_CONTENT_MISMATCH/);}finally{await rm(f.dir,{recursive:true,force:true});}});
test("retention remains fail closed even when reference index proves zero refs",async()=>{const f=await acceptedFixture();try{const{state,g}=await sealedReleased(f);await assert.rejects(commitPhysicalArtifactDeletionV1(f.dir,join(f.dir,"delete.json"),f.artifact,state,g,{...retention,ROLLBACK_ACTIVE:true},{IDEMPOTENCY_KEY:"delete",RUNTIME_NOW_MS:T+6}),/RETENTION_DENIED:ROLLBACK_UNKNOWN_OR_ACTIVE/);}finally{await rm(f.dir,{recursive:true,force:true});}});
